Feat/add redirect location to ovh_iploadbalancing_http_frontend
ovh/terraform-provider-ovh pull request #132
Opened 2020-01-27 16:34 UTC by DamienJ-wiza

[Issue](https://github.com/terraform-providers/terraform-provider-ovh/issues/131)

2020-02-03 15:07 UTC, yanndegat commented on ovh/types_iploadbalancing.go
> +	RedirectLocation string   `json:"redirectLocation,omitempty"`
i think should be *string as the attribute is optional

2020-02-03 15:08 UTC, yanndegat commented on ovh/resource_ovh_iploadbalancing_http_frontend.go
> +		RedirectLocation: d.Get("redirect_location").(string),
if we switch to *string, then we should use getNilStringPointerFromData(d, "redirect_localtion")

2020-02-03 15:09 UTC, yanndegat commented on ovh/resource_ovh_iploadbalancing_http_frontend.go
> +		RedirectLocation: d.Get("redirect_location").(string),
if we switch to *string, then we should use getNilStringPointerFromData(d, "redirect_localtion")

2020-02-03 15:11 UTC, yanndegat commented on ovh/resource_ovh_iploadbalancing_http_frontend.go
> +	d.Set("redirect_location", r.RedirectLocation)
as *string: should be 
if r.RedirectLocation != nil {
d.Set("redirect_location", *r.RedirectLocation)
}

2020-02-03 15:13 UTC, yanndegat commented on website/docs/r/iploadbalancing_http_frontend.markdown
> +* `redirect_location` - Redirection HTTP'
usually, i try to "copy/paste" the official api field description
( but im not always consistent on this)

"HTTP redirection (Ex : http://www.ovh.com)"

2020-11-26 09:17 UTC, pgaxatte requested changes
Discussed with @yanndegat maybe we don't need to change the `string` to `*string` on RedirectLocation and we can add a test later on to see if it is needed or not.

The two indentation problems have likely been introduced by your conflict resolution @yanndegat

2020-11-26 09:17 UTC, pgaxatte commented on ovh/resource_ovh_iploadbalancing_http_frontend.go
> +    RedirectLocation: d.Get("redirect_location").(string),
This indentation has shifted

2020-11-26 09:17 UTC, pgaxatte commented on ovh/resource_ovh_iploadbalancing_http_frontend.go
> +    Disabled:         d.Get("disabled").(bool),
This indentation has shifted

2020-11-26 09:21 UTC, yanndegat approved these changes

2020-11-26 09:22 UTC, pgaxatte approved these changes
All good now, lgtm

2020-11-26 09:22 UTC, merged