K8s
ovh/terraform-provider-ovh pull request #180
Opened 2020-12-15 14:13 UTC by d33d33

2020-12-15 15:50 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#81.0 ✔ 
* 
  * checks ✔

2020-12-15 16:56 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#81.0 ✔ 
* 
  * checks ✔

2020-12-16 07:54 UTC, yanndegat commented
hi @d33d33, @PhilippeVienne 

thanks for this PR, this is great work.

first global remark: some files should be renamed accordlingly to the resources/datasources they define.
eg: ovh/resource_ovh_cloud_kubernetes_cluster.go -> ovh/resource_ovh_cloud_project_kube.go


ovh/data_source_ovh_cloud_kubernetes_cluster.go 
ovh/data_source_ovh_cloud_kubernetes_cluster_test.go
ovh/resource_ovh_cloud_kubernetes_cluster.go
ovh/resource_ovh_cloud_kubernetes_node_pool_test.go 
ovh/resource_ovh_cloud_kubernetes_node_pool.go
ovh/resource_ovh_cloud_kubernetes_cluster_test.go

2020-12-16 09:45 UTC, yanndegat requested changes
hi @d33d33, @PhilippeVienne 

thanks for this PR, this is great work.

this is probably going to be merged in the next release. there are still some stuff to be done yet. 
i'll make general comments here and more precise ones inline.

# resource naming

resources/datasources should be named after their api path
so the nodepool is should be renamed:
ovh_cloud_project_kube_node_pool -> ovh_cloud_project_kube_nodepool


# file naming
first global remark: some files should be renamed accordlingly to the resources/datasources they define.
eg: ovh/resource_ovh_cloud_kubernetes_cluster.go -> ovh/resource_ovh_cloud_project_kube.go


ovh/data_source_ovh_cloud_kubernetes_cluster.go 
ovh/data_source_ovh_cloud_kubernetes_cluster_test.go
ovh/resource_ovh_cloud_kubernetes_cluster.go
ovh/resource_ovh_cloud_kubernetes_node_pool_test.go 
ovh/resource_ovh_cloud_kubernetes_node_pool.go
ovh/resource_ovh_cloud_kubernetes_cluster_test.go 

# documentation

documentation files are missing. there should be a doc file for each datasource/resource file added
ovh/data_source_ovh_cloud_project_kube.go 
ovh/resource_ovh_cloud_project_kube.go
ovh/resource_ovh_cloud_project_kube_node_pool.go

# commits

could you squash your commits before we merge ?

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_cluster.go
> +		r := &PublicCloudProjectKubeResponse{}
should be CloudProjectKubeResponse

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_cluster.go
> +		r := &PublicCloudProjectKubeResponse{}
CloudProjectKubeResponse

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_cluster_test.go
> +	project_id  = "%s"
should be service_name

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_cluster_test.go
> +
a sweeper function has to be implemented

example here
https://github.com/ovh/terraform-provider-ovh/blob/master/ovh/resource_ovh_iploadbalancing_tcp_farm_test.go#L56

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool_test.go
> +`, os.Getenv("OVH_PUBLIC_CLOUD"), os.Getenv("OVH_KUBERNETES_CLUSTER_NAME"), os.Getenv("OVH_PUBLIC_CLOUD"))
should be OVH_CLOUD_PROJECT_SERVICE_TEST and OVH_CLOUD_PROJECT_KUBE_NAME_TEST

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool_test.go
> +	project_id  = "%s"
shloud be service_name

2020-12-16 09:45 UTC, yanndegat commented on ovh/types_cloud.go
> +type PublicCloudProjectKubeResponse struct {
shloud be CloudProjectKubeResponse

2020-12-16 09:45 UTC, yanndegat commented on ovh/types_cloud.go
> +type CloudProjectKubeNodePoolCreationRequest struct {
should be CloudProjectKubeNodePoolCreateOpts

2020-12-16 09:45 UTC, yanndegat commented on ovh/types_cloud.go
> +type CloudProjectKubeNodePoolUpdateRequest struct {
shloud be CloudProjectKubeNodePoolUpdateOpts

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +			"project_id": {
should be service_name

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +				DefaultFunc: schema.EnvDefaultFunc("OVH_PROJECT_ID", nil),
should be OVH_CLOUD_PROJECT_SERVICE

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +	projectId := d.Get("project_id").(string)
should be service_name

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +	projectId := d.Get("project_id").(string)
should be service_name

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +	projectId := d.Get("project_id").(string)
should be service_name

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +	projectId := d.Get("project_id").(string)
should be service_name

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +	_ = d.Set("status", cluster.Status)
remove _=

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +	d.Partial(true)
to be removed

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +	d.Partial(false)
to be removed

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +	d.Partial(false)
return resourceCloudProjectKubeNodePoolRead(d, meta)

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +	d.Partial(true)
to be removed

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +		})
we dont do this elsewhere, return err instead

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +	}
replace with same logic as in ovh_cloud_project_kube create

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +	return nil
return resourceCloudProjectKubeNodePoolRead(d, meta)

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +	d.Partial(true)
to be removed

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +	}
add  CheckDeleted

eg:
```
if err := config.OVHClient.Get(endpoint, r); err != nil {
       return helpers.CheckDeleted(d, err, endpoint)                                                                                                                                                                                   
  }
```

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +	d.Partial(false)
to be removed

2020-12-16 09:45 UTC, yanndegat commented on ovh/resource_ovh_cloud_kubernetes_node_pool.go
> +	return
return nil

2020-12-16 14:16 UTC, pgaxatte commented on ovh/data_source_ovh_cloud_kubernetes_cluster.go
> +			"project_id": {
There's a typo, it's `service_name`

2020-12-18 15:22 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#85.0 ✔ 
* 
  * checks ✔

2020-12-18 16:04 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#86.0 ✔ 
* 
  * checks ✔

2020-12-18 17:23 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#86.0 ✔ 
* 
  * checks ✔

2020-12-23 08:16 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#92.0 ✔ 
* 
  * checks ✔

2020-12-23 09:14 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#92.0 ✔ 
* 
  * checks ✔

2020-12-23 11:17 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#93.0 ✔ 
* 
  * checks ✔

2020-12-23 12:21 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#93.0 ✔ 
* 
  * checks ✔

2021-01-21 15:46 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#123.0 ✔ 
* 
  * checks ✔

2021-01-21 16:20 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#123.0 ✘  
* 
  * checks ✘

2021-01-21 17:57 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#124.0 ✔ 
* 
  * checks ✔

2021-01-21 19:17 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#124.0 ✔ 
* 
  * checks ✔

2021-01-22 16:03 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#126.0 ✘  
* 
  * checks ✘

2021-01-22 16:03 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#126.0 ✘  
* 
  * checks ✘

2021-01-26 11:41 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#126.1 ✘  
* 
  * checks ✘

2021-01-26 11:41 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#126.1 ✘  
* 
  * checks ✘

2021-01-26 13:05 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#131.0 ✔ 
* 
  * checks ✔

2021-01-26 14:07 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#131.0 ✔ 
* 
  * checks ✔

2021-03-02 16:22 UTC, yanndegat approved these changes

2021-03-02 16:22 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#167.0 ✔ 
* 
  * checks ✔

2021-03-02 17:27 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#167.0 ✘  
* 
  * checks ✘

2021-03-02 19:26 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#167.1 ✔ 
* 
  * checks ✔

2021-03-03 08:00 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#169.0 ✔ 
* 
  * checks ✔

2021-03-03 08:02 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#169.0 ✘  
* 
  * checks ✘

2021-03-03 08:05 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#169.1 ■

2021-03-03 08:05 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#169.1 ■

2021-03-03 08:05 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#169.0 ✔ 
* 
  * checks ✔

2021-03-03 08:06 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#169.2 ✘  
* 
  * checks ✘

2021-03-03 09:06 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#169.3 ✘  
* 
  * checks ✘

2021-03-03 10:34 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#169.4 ✔ 
* 
  * checks ✔

2021-03-03 14:14 UTC, merged

2021-03-03 14:14 UTC, yanndegat commented
finally

thanks to all of you @PhilippeVienne @d33d33