Webhosting privatedatabase
ovh/terraform-provider-ovh pull request #247
Opened 2022-04-05 07:30 UTC by wiseflat

Hi,

This PR will add features to deploy privatesql databases as code.

2022-09-15 11:56 UTC, pgaxatte approved these changes
Awesome work, it's all good to me!

2022-09-20 09:09 UTC, scraly commented
Hi,
thanks for your PR :).

Is it possible to fix your acceptance test in order to be able to execute all of them, without any order.
For example, in an acceptance test of a datasource you need to create the resource.
You can find a lot of examples of test acceptance of a datasource in the repository :).

2022-09-21 08:32 UTC, scraly commented on website/docs/r/hosting_privatedatabase.html.markdown
> +* `ovh_subsidiary` - (Required) Ovh Subsidiary
```suggestion
* `ovh_subsidiary` - (Required) OVHcloud Subsidiary
```

2022-09-21 08:32 UTC, scraly commented on website/docs/r/hosting_privatedatabase.html.markdown
> +* `payment_mean` - (Required) Ovh payment mode (One of "default-payment-mean", "fidelity", "ovh-account")
```suggestion
* `payment_mean` - (Required) OVHcloud payment mode (One of "default-payment-mean", "fidelity", "ovh-account")
```

2022-09-21 08:32 UTC, scraly commented on website/docs/r/hosting_privatedatabase.html.markdown
> +* `hostname_ftp` - Private database ftp hostname
```suggestion
* `hostname_ftp` - Private database FTP hostname
```

2022-09-21 08:32 UTC, scraly commented on website/docs/r/hosting_privatedatabase.html.markdown
> +* `cpu` - Number of cpu on your private database
```suggestion
* `cpu` - Number of CPU on your private database
```

2022-09-21 08:35 UTC, scraly commented on website/docs/r/hosting_privatedatabase_database.html.markdown
> +## Import
Please follow the same import block like other resources.
Example:

```

## Import

OVHcloud Managed Kubernetes Service clusters can be imported using the `serviceName` and the `id` of the cluster, separated by "/" E.g.,

```bash
$ terraform import ovh_cloud_project_kube.my_kube_cluster service_name/kube_id
```

2022-09-21 08:37 UTC, scraly commented on website/docs/r/hosting_privatedatabase_user.html.markdown
> +## Import
Same remark, please follow the other import block example

2022-09-21 08:37 UTC, scraly commented on website/docs/r/hosting_privatedatabase_user_grant.html.markdown
> +## Import
same remark for import block like others with an example

2022-09-21 08:40 UTC, scraly commented on website/docs/r/hosting_privatedatabase_whitelist.html.markdown
> +* `sftp` - (Required) Authorize this IP to access sftp port. Values can be `true` or `false`
```suggestion
* `sftp` - (Required) Authorize this IP to access SFTP port. Values can be `true` or `false`
```

2022-09-21 08:40 UTC, scraly commented on website/docs/r/hosting_privatedatabase_whitelist.html.markdown
> +## Import
same remark :)

2022-09-21 08:40 UTC, scraly commented on website/docs/d/hosting_privatedatabase.html.markdown
> +* `cpu` - Number of cpu on your private database
```suggestion
* `cpu` - Number of CPU on your private database
```

2022-09-21 08:40 UTC, scraly commented on website/docs/d/hosting_privatedatabase.html.markdown
> +* `hostname_ftp` - Private database ftp hostname
```suggestion
* `hostname_ftp` - Private database FTP hostname
```

2022-09-21 08:40 UTC, scraly commented on website/docs/d/hosting_privatedatabase.html.markdown
> +* `port_ftp` - Private database ftp port
```suggestion
* `port_ftp` - Private database FTP port
```

2022-09-21 08:41 UTC, scraly commented on website/docs/d/hosting_privatedatabase_database.html.markdown
> +* `backup_time` - Time of the next backup ( every day )
```suggestion
* `backup_time` - Time of the next backup (every day)
```

2022-09-21 08:41 UTC, scraly commented on website/docs/d/hosting_privatedatabase_whitelist.html.markdown
> +* `sftp` - Authorize this IP to access sftp port
```suggestion
* `sftp` - Authorize this IP to access SFTP port
```

2022-09-21 08:42 UTC, scraly commented on ovh/data_hosting_privatedatabase.go
> +				Description: "Number of cpu on your private database",
```suggestion
				Description: "Number of CPU on your private database",
```

2022-09-21 08:42 UTC, scraly commented on ovh/data_hosting_privatedatabase.go
> +				Description: "Private database ftp hostname",
```suggestion
				Description: "Private database FTP hostname",
```

2022-09-21 08:42 UTC, scraly commented on ovh/data_hosting_privatedatabase.go
> +				Description: "Private database ftp port",
```suggestion
				Description: "Private database FTP port",
```

2022-09-21 08:44 UTC, scraly commented on ovh/data_hosting_privatedatabase_whitelist.go
> +				Description: "Authorize this IP to access sftp port",
```suggestion
				Description: "Authorize this IP to access SFTP port",
```

2022-09-21 08:45 UTC, scraly commented on ovh/hosting_privatedatabase.go
> +			log.Printf("[DEBUG][WaitArchivedHostingPrivateDabaseTask] weird error ... ")
weird? :-D

2022-09-21 08:45 UTC, scraly commented on ovh/hosting_privatedatabase.go
> +		log.Printf("[DEBUG][WaitArchivedHostingPrivateDabaseTask] archived ! ")
```suggestion
		log.Printf("[DEBUG][WaitArchivedHostingPrivateDabaseTask] archived!")
```

2022-09-21 08:46 UTC, scraly commented on ovh/hosting_privatedatabase.go
> +			log.Printf("[DEBUG][WaitArchivedHostingPrivateDabaseTask] weird error ... ")
```suggestion
			log.Printf("[DEBUG][WaitArchivedHostingPrivateDabaseTask] weird error ...")
```

2022-09-21 08:48 UTC, scraly commented on ovh/import_hosting_privatedatabase_user_grant_test.go
> +	resourceName := "ovh_hosting_privatedatabase_user_grant.grant"
You need to add new environment variable in the documentation too:
https://registry.terraform.io/providers/ovh/ovh/latest/docs#testing-and-development

2022-11-23 14:55 UTC, scraly requested changes

2022-11-23 14:55 UTC, scraly commented on website/docs/d/hosting_privatedatabase_database.html.markdown
> + database_name  = "XXXXXX"
```suggestion
  database_name  = "XXXXXX"
```

2022-11-23 14:55 UTC, scraly commented on website/docs/d/hosting_privatedatabase_user.html.markdown
> + service_name  = "XXXXXX"
```suggestion
  service_name  = "XXXXXX"
```

2022-11-23 14:55 UTC, scraly commented on website/docs/d/hosting_privatedatabase_user.html.markdown
> + user_name  = "XXXXXX"
```suggestion
  user_name  = "XXXXXX"
```

2022-11-23 14:55 UTC, scraly commented on website/docs/d/hosting_privatedatabase_user.html.markdown
> +data "ovh_hosting_privatedatabase_user" "description" {
```suggestion
data "ovh_hosting_privatedatabase_user" "user" {
```

2022-11-23 14:55 UTC, scraly commented on website/docs/d/hosting_privatedatabase_user_grant.html.markdown
> +data "ovh_hosting_privatedatabase_user_grant" "description" {
```suggestion
data "ovh_hosting_privatedatabase_user_grant" "user_grant" {
```

2022-11-23 14:55 UTC, scraly commented on website/docs/d/hosting_privatedatabase_user_grant.html.markdown
> + service_name  = "XXXXXX"
```suggestion
  service_name  = "XXXXXX"
```

2022-11-23 14:55 UTC, scraly commented on website/docs/d/hosting_privatedatabase_user_grant.html.markdown
> + database_name = "XXXXXX"
```suggestion
  database_name = "XXXXXX"
```

2022-11-23 14:55 UTC, scraly commented on website/docs/d/hosting_privatedatabase_user_grant.html.markdown
> + user_name     = "XXXXXX"
```suggestion
  user_name     = "XXXXXX"
```

2022-11-23 14:55 UTC, scraly commented on website/docs/d/hosting_privatedatabase_whitelist.html.markdown
> +data "ovh_hosting_privatedatabase_whitelist" "description" {
```suggestion
data "ovh_hosting_privatedatabase_whitelist" "whitelist" {
```

2022-11-23 14:55 UTC, scraly commented on website/docs/d/hosting_privatedatabase_whitelist.html.markdown
> + service_name  = "XXXXXX"
```suggestion
  service_name  = "XXXXXX"
```

2022-11-23 14:55 UTC, scraly commented on website/docs/d/hosting_privatedatabase_whitelist.html.markdown
> + ip            = "XXXXXX"
```suggestion
  ip            = "XXXXXX"
```

2022-11-23 14:55 UTC, scraly commented on website/docs/r/hosting_privatedatabase_user_grant.html.markdown
> +resource "ovh_hosting_privatedatabase_user_grant" "user" {
```suggestion
resource "ovh_hosting_privatedatabase_user_grant" "user_grant" {
```

2022-11-23 14:55 UTC, scraly commented on website/docs/d/hosting_privatedatabase.html.markdown
> +* `service_name` - The service name
```suggestion
* `service_name` - The internal name of your private database
```

2022-11-23 15:19 UTC, scraly requested changes

2022-11-23 15:19 UTC, scraly commented on ovh/data_hosting_privatedatabase.go
> +func dataSourceHostingPrivateDatabaseRead(d *schema.ResourceData, meta interface{}) error {
Small question:

What about setting the endpoint and dynamically the fields, like other datasources?
Example:

```
func dataSourcexxxxRead(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*Config)
	serviceName := d.Get("service_name").(string)

	endpoint := fmt.Sprintf("/xx/xx/%s/kube/%s/xx", serviceName)
	res := &xxxxResponse{}

	log.Printf("[DEBUG] Will read xx from xx %s and xx: %s", xx, serviceName)
	err := config.OVHClient.Get(endpoint, res)
	if err != nil {
		return fmt.Errorf("calling get %s %w", endpoint, err)
	}
	for k, v := range res.ToMap() {
		if k != "id" {
			d.Set(k, v)
		}
	}
	d.SetId(xxId + "-" + res.ClientID + "-" + res.IssuerUrl)

	log.Printf("[DEBUG] Read xx %+v", res)
	return nil
} 
```

2022-11-29 10:50 UTC, scraly approved these changes

2022-11-29 10:51 UTC, scraly commented
Thanks! :)

2022-11-29 10:51 UTC, merged