Add feature to set catalogName on order_cart
ovh/terraform-provider-ovh pull request #250
Opened 2022-04-08 15:52 UTC by wiseflat

I need to set a specific catalogName to order some resources.
Requirement for that is to assign a shopping cart to a loggedin client

2022-11-09 08:57 UTC, scraly requested changes
Thanks :) 

I have just one remark, is it possible to change in the datasource documentation:

```
description    = "..."
```

to:
```
description    = "my cart"
```

2022-11-28 16:23 UTC, wiseflat commented
Done 👍

2022-11-29 08:47 UTC, scraly approved these changes

2022-11-29 08:47 UTC, scraly commented
Thanks, it's now ok for me :)

2022-11-29 08:47 UTC, merged