Kube/OIDC
ovh/terraform-provider-ovh pull request #273
Opened 2022-07-06 15:27 UTC by matprig

Hello,

This PR contains:
- kube OIDC parameter resource
- documentation
- test acceptance
best

2022-07-12 15:12 UTC, XavierDuthil requested changes

2022-07-12 15:24 UTC, XavierDuthil requested changes

2022-07-12 15:24 UTC, XavierDuthil commented on ovh/resource_cloud_project_kube_oidc.go
> +		if k != "id" {
I would have inverted the conditions

2022-07-13 07:15 UTC, matprig commented on ovh/resource_cloud_project_kube_oidc.go
> +}
- [ ] true need to do gofumtp on all files on all PRs

2022-07-13 07:26 UTC, matprig commented on ovh/resource_cloud_project_kube_oidc.go
> +		return fmt.Errorf("calling Post %s with params %s:\n\t %q", endpoint, params, err)
- [ ] true this is a point, i did not notice that the whole project was not wrapping errors %w directive

2022-07-13 15:28 UTC, XavierDuthil commented on ovh/resource_cloud_project_kube_oidc.go
> +}
/approve

2022-07-25 14:23 UTC, scraly requested changes

2022-07-25 14:23 UTC, scraly commented on website/docs/r/cloud_project_kube_oidc.html.markdown
> +Creates an oidc configuration in a kubernetes managed cluster.
```suggestion
Creates an OIDC configuration in an OVHcloud Managed Kubernetes cluster.
```

2022-07-25 14:23 UTC, scraly commented on website/docs/r/cloud_project_kube_oidc.html.markdown
> +Creates a oidc configuration in a OVH Managed Kubernetes Service cluster.
```suggestion
Creates an OIDC configuration in an OVHcloud Managed Kubernetes cluster.
```

2022-07-25 14:23 UTC, scraly commented on website/docs/r/cloud_project_kube_oidc.html.markdown
> +* `service_name` - (required) The id of the public cloud project. If omitted,
```suggestion
* `service_name` - (required) The ID of the public cloud project. If omitted,
```

2022-07-25 14:23 UTC, scraly commented on website/docs/r/cloud_project_kube_oidc.html.markdown
> +* `kube_id` - The id of the managed kubernetes cluster.
```suggestion
* `kube_id` - The ID of the managed kubernetes cluster.
```

2022-07-25 14:23 UTC, scraly commented on website/docs/r/cloud_project_kube_oidc.html.markdown
> +  kube_id      = ovh_cloud_project_kube.k8stf.id
```suggestion
  kube_id      = ovh_cloud_project_kube. mykube.id
```

2022-07-25 14:23 UTC, scraly commented on ovh/types_cloud.go
> +	// Dont set password as it must be set only at creation time
```suggestion
	// Don't set password as it must be set only at creation time
```

2022-07-25 14:41 UTC, scraly commented
![OIDC provider](https://user-images.githubusercontent.com/2543381/180804154-43dd7a96-4d55-45c7-8990-cf0b1c502109.png)

🙂

2022-07-25 14:53 UTC, scraly requested changes

2022-07-25 14:53 UTC, scraly commented on ovh/resource_cloud_project_kube_oidc_test.go
> +		"yyy",
```suggestion
		"my-another-oidc-client-id",
```

2022-07-25 14:53 UTC, scraly commented on ovh/resource_cloud_project_kube_oidc_test.go
> +		"xxx",
```suggestion
		"my-oidc-client-id",
```

2022-07-25 14:53 UTC, scraly commented on ovh/resource_cloud_project_kube_oidc_test.go
> +						"ovh_cloud_project_kube_oidc.my-oidc", "client_id", "yyy"),
```suggestion
						"ovh_cloud_project_kube_oidc.my-oidc", "client_id", "my-another-oidc-client-id"),
```

2022-07-25 14:53 UTC, scraly commented on ovh/resource_cloud_project_kube_oidc_test.go
> +						"ovh_cloud_project_kube_oidc.my-oidc", "client_id", "xxx"),
```suggestion
						"ovh_cloud_project_kube_oidc.my-oidc", "client_id", "my-oidc-client-id"),
```

2022-07-26 07:21 UTC, scraly requested changes

2022-07-26 07:21 UTC, scraly commented on website/docs/r/cloud_project_kube_oidc.html.markdown
> +  kube_id      = ovh_cloud_project_kube. mykube.id
```suggestion
  kube_id      = ovh_cloud_project_kube.mykube.id
```

2022-07-26 12:07 UTC, scraly approved these changes

2022-07-26 12:07 UTC, merged