Add generic user provider and postgresql user provider
ovh/terraform-provider-ovh pull request #278
Opened 2022-07-19 14:45 UTC by lpatte

Generic user provider is for engine : 

- Cassandra
- Kafka
- KafkaConnect
- Mysql

2022-07-22 08:38 UTC, ybriffa requested changes

2022-07-22 08:38 UTC, ybriffa commented on ovh/resource_cloud_project_database_user.go
> +				Description: "Date of the creation of the cluster",
wrong description

2022-07-22 08:38 UTC, ybriffa commented on ovh/resource_cloud_project_database_postgresql_user.go
> +				Description: "Date of the creation of the cluster",
wrong description

2022-07-22 08:38 UTC, ybriffa commented on website/docs/d/cloud_project_database_users.html.markdown
> +* `engine` - The database engine you want to deploy. To get a full list of available engine visit.
wrong description

2022-07-22 08:38 UTC, ybriffa commented on website/docs/r/cloud_project_database_postrgesql_user.html.markdown
> +* `engine` - The database engine you want to deploy. To get a full list of available engine visit.
wrong description

2022-07-22 08:38 UTC, ybriffa commented on website/docs/r/cloud_project_database_user.html.markdown
> +* `engine` - The database engine you want to deploy. To get a full list of available engine visit.
wrong description

2022-07-22 14:29 UTC, ybriffa approved these changes

2022-07-27 09:43 UTC, scraly requested changes

2022-07-27 09:43 UTC, scraly commented on website/docs/d/cloud_project_database_postgresql_user.html.markdown
> +data "ovh_cloud_project_databases_user" "user" {
```suggestion
data "ovh_cloud_project_database_postgresql_user" "pguser" {
```

2022-07-27 09:43 UTC, scraly commented on website/docs/d/cloud_project_database_postgresql_user.html.markdown
> +}
```suggestion
}

output "pguser_roles" {
  value = data.ovh_cloud_project_database_postgresql_user.pguser.roles
}
```

2022-07-27 09:43 UTC, scraly commented on website/docs/d/cloud_project_database_user.html.markdown
> +}
```suggestion
}

output "user_name" {
  value = data.ovh_cloud_project_database_user.user.name
}
```

2022-07-27 09:43 UTC, scraly commented on website/docs/d/cloud_project_database_user.html.markdown
> +data "ovh_cloud_project_databases_user" "user" {
```suggestion
data "ovh_cloud_project_database_user" "user" {
```

2022-07-27 09:43 UTC, scraly commented on website/docs/d/cloud_project_database_user.html.markdown
> +Aivalable engines for this resource (other have specific resource):
```suggestion
Available engines for this resource (other have specific resource):
```

2022-07-27 09:43 UTC, scraly commented on website/docs/d/cloud_project_database_users.html.markdown
> +}
```suggestion
}

output "user_ids" {
  value = data.ovh_cloud_project_database_users.users.user_ids
}
```

2022-07-27 09:43 UTC, scraly commented on website/docs/d/cloud_project_database_users.html.markdown
> +data "ovh_cloud_project_databases_users" "users" {
```suggestion
data "ovh_cloud_project_database_users" "users" {
```

2022-07-28 07:10 UTC, scraly requested changes

2022-07-28 07:10 UTC, scraly commented on website/docs/d/cloud_project_database_postgresql_user.html.markdown
> +* `id` - Public Cloud Database Service ID.
```suggestion
* `id` - ID of the user.
```

2022-07-28 07:10 UTC, scraly commented on website/docs/d/cloud_project_database_user.html.markdown
> +* `id` - Public Cloud Database Service ID.
```suggestion
* `id` - ID of the user.
```

2022-07-28 07:44 UTC, scraly approved these changes

2022-07-28 07:44 UTC, scraly commented
Thanks :)

2022-07-28 07:44 UTC, merged