Add MongoDB and Redis user provider
ovh/terraform-provider-ovh pull request #283
Opened 2022-08-09 09:44 UTC by lpatte

- MongoDB User Lifecycle
- Redis User Lifecycle
- Import Test for Cloud Databases resources

2022-08-09 14:44 UTC, lpatte commented
@ovh/cloud-databases please review

2022-08-10 07:42 UTC, BellionBastien commented on ovh/resource_cloud_project_database_mongodb_user.go
> +	err = waitForCloudProjectDatabaseReady(config.OVHClient, serviceName, "mongodb", clusterId, 60*time.Second, 10*time.Second)
Here you should wait for the user to be properly created waiting for the status to be set at "READY" Same goes for other user engines

2022-08-10 07:42 UTC, BellionBastien commented on ovh/resource_cloud_project_database_mongodb_user.go
> +	err = waitForCloudProjectDatabaseReady(config.OVHClient, serviceName, "mongodb", clusterId, 60*time.Second, 10*time.Second)
Here you should wait for the user to be properly created waiting for the status to be set at "READY" Same goes for other user engines

2022-08-10 07:42 UTC, BellionBastien commented on ovh/resource_cloud_project_database_mongodb_user.go
> +			//Optional/Computed
User should not be able to set it's password. This endpoint will be deprecated, we don't want user to get use to use this "feature"

2022-08-10 07:42 UTC, BellionBastien commented on ovh/resource_cloud_project_database_redis_user.go
> +	err = waitForCloudProjectDatabaseReady(config.OVHClient, serviceName, "redis", clusterId, 60*time.Second, 10*time.Second)
Here you should wait for the user to be properly created waiting for the status to be set at "READY"

2022-08-10 07:42 UTC, BellionBastien commented on ovh/resource_cloud_project_database_redis_user.go
> +	log.Printf("[DEBUG] Waiting for database %s to be READY", clusterId)
Here you should wait for the user to be properly created waiting for the status to be set at "READY"

2022-08-10 12:20 UTC, BellionBastien commented on ovh/resource_cloud_project_database_mongodb_user.go
> +	log.Printf("[DEBUG] Waiting for database %s to be DELETED", id)
Message shoud be "[DEBUG] Waiting for user %s to be DELETED"

2022-08-10 12:20 UTC, BellionBastien commented on ovh/resource_cloud_project_database_postgresql_user.go
> +	log.Printf("[DEBUG] Waiting for database %s to be DELETED", id)
message should be" [DEBUG] Waiting for user %s to be DELETED"

2022-08-10 12:20 UTC, BellionBastien commented on ovh/resource_cloud_project_database_redis_user.go
> +	log.Printf("[DEBUG] Waiting for database %s to be DELETED", id)
Message shoud be "[DEBUG] Waiting for user %s to be DELETED"

2022-08-10 12:20 UTC, BellionBastien commented on ovh/resource_cloud_project_database_user.go
> +	log.Printf("[DEBUG] Waiting for database %s to be DELETED", id)
message should be "[DEBUG] Waiting for user %s to be DELETED"

2022-08-12 07:03 UTC, BellionBastien approved these changes

2022-08-19 08:50 UTC, scraly commented
review in progress

one modification to do in the doc please:

```
resource "ovh_cloud_project_database" "mongodb" {
  service_name = var.openstack_infos.project_id
```
 
 ```
 resource "ovh_cloud_project_database" "mongodb" {
  service_name = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```

:)

2022-08-19 11:42 UTC, scraly requested changes

2022-08-19 11:42 UTC, scraly commented on website/docs/d/cloud_project_database_redis_user.html.markdown
> +* `channels` - Channels of the user.
```suggestion
* `channels` - Channels of the user.
* `cluster_id` - ID of the cluster.
```

2022-08-19 11:42 UTC, scraly commented on ovh/data_cloud_project_database_mongodb_user_test.go
> +	version := os.Getenv("OVH_CLOUD_PROJECT_DATABASE_POSTGRESQL_VERSION_TEST")
```suggestion
	version := os.Getenv("OVH_CLOUD_PROJECT_DATABASE_MONGODB_VERSION_TEST")
```

2022-08-19 11:42 UTC, scraly commented on ovh/data_cloud_project_database_redis_user_test.go
> +	version := os.Getenv("OVH_CLOUD_PROJECT_DATABASE_POSTGRESQL_VERSION_TEST")
```suggestion
	version := os.Getenv("OVH_CLOUD_PROJECT_DATABASE_REDIS_VERSION_TEST")
```

2022-08-19 11:42 UTC, scraly commented on ovh/import_cloud_project_database_redis_user_test.go
> +	version := os.Getenv("OVH_CLOUD_PROJECT_DATABASE_POSTGRESQL_VERSION_TEST")
```suggestion
	version := os.Getenv("OVH_CLOUD_PROJECT_DATABASE_REDIS_VERSION_TEST")
```

2022-08-19 16:23 UTC, lpatte commented on website/docs/d/cloud_project_database_mongodb_user.html.markdown
> +* `name` - Name of the user.
password is not exported in datasource, only in resource

2022-08-23 13:43 UTC, scraly commented
Thanks, it's OK for me :)

2022-08-23 13:43 UTC, merged