Add S3 Credential datasource and resource
ovh/terraform-provider-ovh pull request #291
Opened 2022-08-21 15:14 UTC by yvigara

Add the datasources and resource to create and retrieve S3 Credentials (AccessKeyId and SecretAccessKey) required to access S3 buckets. Fixes #285

2022-08-24 09:39 UTC, scraly commented
Hi,
thanks for the PR, it's a good addition :)

I have an issue with the first acceptance test:
![image](https://user-images.githubusercontent.com/2543381/186385866-e9241a08-25da-4446-b6ac-6f235c33cf80.png)

2022-08-24 09:40 UTC, scraly requested changes

2022-08-24 09:40 UTC, scraly commented on website/docs/r/cloud_project_user_s3_credential.html.markdown
> + description  = "my user for acceptance tests"
In order to help user about how they can create this resource, adding a role_name can be useful.

For example:
```
role_name = "administrator"
```

or specify a list of role_names for the example

2022-08-24 09:40 UTC, scraly commented on website/docs/r/cloud_project_user_s3_credential.html.markdown
> +- `service_name` - (Required) The id of the public cloud project. If omitted,
```suggestion
- `service_name` - (Required) The ID of the public cloud project. If omitted,
```

2022-08-24 09:40 UTC, scraly commented on website/docs/r/cloud_project_user_s3_credential.html.markdown
> +- `user_id` - (Required) The id of a public cloud project's user.
```suggestion
- `user_id` - (Required) The ID of a public cloud project's user.
```

2022-08-24 09:40 UTC, scraly commented on website/docs/d/cloud_project_user_s3_credentials.html.markdown
> +}
```suggestion
}

output "access_key_ids" {
    value = data.ovh_cloud_project_user_s3_credentials.myuser.access_key_ids
}
```

2022-08-24 09:40 UTC, scraly commented on website/docs/d/cloud_project_user_s3_credentials.html.markdown
> +data "ovh_cloud_project_user_s3_credentials" "user_1234_s3_credentials" {
```suggestion
data "ovh_cloud_project_user_s3_credentials" "myuser" {
```

2022-08-24 09:40 UTC, scraly commented on website/docs/d/cloud_project_user_s3_credentials.html.markdown
> +- `service_name` - (Required) The id of the public cloud project. If omitted,
```suggestion
- `service_name` - (Required) The ID of the public cloud project. If omitted,
```

2022-08-24 09:40 UTC, scraly commented on website/docs/d/cloud_project_user_s3_credentials.html.markdown
> +- `user_id` - (Required) The id of a public cloud project's user.
```suggestion
- `user_id` - (Required) The ID of a public cloud project's user.
```

2022-08-24 09:40 UTC, scraly commented on website/docs/d/cloud_project_user_s3_credential.html.markdown
> +data "ovh_cloud_project_user_s3_credentials" "s3_credentials" {
Useless if we set manually the user_id in the `ovh_cloud_project_user_s3_credential` datasource.

2022-08-24 09:40 UTC, scraly commented on website/docs/d/cloud_project_user_s3_credential.html.markdown
> +data "ovh_cloud_project_user_s3_credential" "s3_cred_1" {
suggestion:

```
data "ovh_cloud_project_user_s3_credential" "mycred" {
   service_name = var.service_name
   user_id      = "244435"
   access_key_id = "xxxx"
}

output "myaccesskey" {
    value = ovh_cloud_project_user_s3_credential.s3_credential.access_key_id
}

output "mysecretaccesskey" {
    value = ovh_cloud_project_user_s3_credential.s3_credential.secret_access_key
    sensitive = true
}
```

or, if we want to use the datasource that list the access_key_id:

```
data "ovh_cloud_project_user_s3_credential" "mycred" {
   service_name = var.service_name
   user_id      = data.ovh_cloud_project_user_s3_credentials.myadmin.user_id
   access_key_id = data.ovh_cloud_project_user_s3_credentials.myadmin.access_key_ids[0]
}

output "myaccesskey" {
    value = ovh_cloud_project_user_s3_credential.s3_credential.access_key_id
}

output "mysecretaccesskey" {
    value = ovh_cloud_project_user_s3_credential.s3_credential.secret_access_key
    sensitive = true
}
```

2022-08-24 09:59 UTC, scraly commented
About acceptance test, is it possible them like this example?
https://github.com/ovh/terraform-provider-ovh/blob/master/ovh/data_cloud_project_database_ip_restrictions_test.go

Thanks

2022-08-24 21:19 UTC, yvigara commented
@scraly thanks a lot for the feedback. All the requested changes should be resolved now.

2022-08-25 14:52 UTC, yvigara commented
Just to be sure, do you mean renaming the config variable to match the test function, keeping it as a simple string and moving the string formatting in the test function?

2022-08-25 14:59 UTC, scraly commented
I mean moving the hash function to another file, next to the resource file.
Thanks to that in this new helpers file, in the future we can add another helper functions to that resource.

2022-08-26 07:02 UTC, scraly commented
Sorry, I reviewed two PRs at the same time so my brain have switched :-D.
About the acceptance test I mean, yes, the const as string and how to pass the config.
Even if a lot of different people contribute to the repo, the goal is to try to keep a coherence when it is possible :).

2022-08-26 09:15 UTC, yvigara commented
Should be all fixed now

2022-08-26 09:59 UTC, scraly approved these changes
Perfect, thanks :-) 
Acceptance tests are well written now and all the tests are in success.

2022-08-26 10:03 UTC, merged