M3DB user and Namespace + Database + capabilities data
ovh/terraform-provider-ovh pull request #313
Opened 2022-09-22 10:35 UTC by lpatte

- M3db user (resource/datasource/import/doc) 
- M3db namespace (resource/datasource/import/doc) 
- database (resource/datasource/import/doc) 
- capabilities (datasource/doc)
- Add field `kafka_rest_api` and `opensearch_acls_enabled` to cloud_project_database (fix https://github.com/ovh/terraform-provider-ovh/issues/309)

2022-09-22 13:51 UTC, scraly requested changes

2022-09-22 13:51 UTC, scraly commented on website/docs/r/cloud_project_database_m3db_namespace.html.markdown
> +Creates a namespace for a m3db cluster associated with a public cloud project.
```suggestion
Creates a namespace for a M3DB cluster associated with a public cloud project.
```

2022-09-22 13:51 UTC, scraly commented on website/docs/r/cloud_project_database_m3db_user.html.markdown
> +Creates an user for a m3db cluster associated with a public cloud project.
```suggestion
Creates a user for a M3DB cluster associated with a public cloud project.
```

2022-09-22 13:51 UTC, scraly commented on website/docs/r/cloud_project_database_m3db_user.html.markdown
> +OVHcloud Managed m3db clusters users can be imported using the `service_name`, `cluster_id` and `id` of the user, separated by "/" E.g.,
```suggestion
OVHcloud Managed M3DB clusters users can be imported using the `service_name`, `cluster_id` and `id` of the user, separated by "/" E.g.,
```

2022-09-22 13:51 UTC, scraly commented on website/docs/d/cloud_project_database_capabilities.html.markdown
> +* `engine` - Database engines available.
```suggestion
* `engines` - Database engines available.
```

2022-09-22 14:56 UTC, scraly requested changes

2022-09-22 14:56 UTC, scraly commented on website/docs/r/cloud_project_database_m3db_namespace.html.markdown
> +  group         = "mygroup"
`retention_period_duration` instead? With an example of the required format please :)

2022-09-22 14:56 UTC, scraly commented on website/docs/r/cloud_project_database_m3db_namespace.html.markdown
> +  name          = "johndoe"
```suggestion
  name          = "my-namespace"
```

2022-09-23 06:05 UTC, scraly requested changes

2022-09-23 06:05 UTC, scraly commented on website/docs/d/cloud_project_database_m3db_namespaces.html.markdown
> +* `namespace_ids` - The list of namespaces ids of the m3db cluster associated with the project.
```suggestion
* `namespace_ids` - The list of namespaces ids of the M3DB cluster associated with the project.
```

2022-09-23 06:05 UTC, scraly commented on website/docs/index.html.markdown
> +* `OVH_CLOUD_PROJECT_DATABASE_M3DB_VERSION_TEST` - The version of the mongodb to test. if not set `OVH_CLOUD_PROJECT_DATABASE_VERSION_TEST` is use.
```suggestion
* `OVH_CLOUD_PROJECT_DATABASE_M3DB_VERSION_TEST` - The version of the M3DB to test. if not set `OVH_CLOUD_PROJECT_DATABASE_VERSION_TEST` is use.
```

2022-09-23 07:43 UTC, scraly requested changes

2022-09-23 07:43 UTC, scraly commented on ovh/data_cloud_project_database_m3db_namespace.go
> +				Description: "Defines whether M3db will include writes to this namespace in the commit log",
```suggestion
				Description: "Defines whether M3DB will include writes to this namespace in the commit log",
```

2022-09-23 07:43 UTC, scraly commented on website/docs/r/cloud_project_database.html.markdown
> +* `opensearch_acls_enabled` -  (Optional) Defines whether the acls are enabled on an Opensearch cluster
```suggestion
* `opensearch_acls_enabled` -  (Optional) Defines whether the ACLs are enabled on an OpenSearch cluster
```

2022-09-23 07:59 UTC, merged

2022-09-23 08:06 UTC, albundy83 commented
Big merge :)
Is there the support to create databases with PostgreSQL ?