Integration and User password reset
ovh/terraform-provider-ovh pull request #321
Opened 2022-10-03 13:52 UTC by lpatte

- Integration (resource/datasource/import/doc)
- Add Password Reset system to user resources (resource/doc)
- Generalize Certificate resources (datasource/doc)

2022-10-04 10:00 UTC, scraly commented on website/docs/r/cloud_project_database_m3db_user.html.markdown
> +
```
output "user_password" {
    value = ovh_cloud_project_database_m3db_user.user.password
    sensitive = true
}
```

2022-10-04 10:23 UTC, scraly commented on website/docs/r/cloud_project_database_m3db_user.html.markdown
> +
speak about the `terraform refresh` command to execute after the apply ... :)

2022-10-04 13:09 UTC, lpatte commented on website/docs/r/cloud_project_database_m3db_user.html.markdown
> +* `password_reset` - (Optional) Arbitrary string to change to trigger a password update.
no it's for all engines

2022-10-05 06:25 UTC, scraly requested changes

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_integration.html.markdown
> +Thanks to the integration feature you can have your postgreSQL logs in your OpenSearch DB
```suggestion
Please take a look at the list of available `types` in the Àrgument references` section in order to know the list of avaulable integrations. For example, thanks to the integration feature you can have your PostgreSQL logs in your OpenSearch Database.
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_m3db_user.html.markdown
> +To reset password of the user previouly create, update the `password_reset` attribut.
```suggestion
-> __NOTE__ To reset password of the user previously created, update the `password_reset` attribute.
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_m3db_user.html.markdown
> +Use command `terraform refresh` after `terraform apply` to update output with new password.
```suggestion
Use command `terraform refresh` after executing `terraform apply` to update the output with new password.
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_m3db_user.html.markdown
> +* `password_reset` - (Optional) Arbitrary string to change to trigger a password update. Use command `terraform refresh` after `terraform apply` to update output with new password.
```suggestion
* `password_reset` - (Optional) Arbitrary string to change to trigger a password update. Use command `terraform refresh` after executing `terraform apply` to update the output with new password.
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_mongodb_user.html.markdown
> +Create a user johndoe in a mongodb database.
```suggestion
Create a user johndoe in a MongoDB database.
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_mongodb_user.html.markdown
> +To reset password of the user previouly create, update the `password_reset` attribut.
```suggestion
-> __NOTE__ To reset password of the user previously created, update the `password_reset` attribute.
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_mongodb_user.html.markdown
> +Use command `terraform refresh` after `terraform apply` to update output with new password.
```suggestion
Use command `terraform refresh` after executing `terraform apply` to update the output with new password.
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_mongodb_user.html.markdown
> +* `password_reset` - (Optional) Arbitrary string to change to trigger a password update. Use command `terraform refresh` after `terraform apply` to update output with new password.
```suggestion
* `password_reset` - (Optional) Arbitrary string to change to trigger a password update. Use the `terraform refresh` command after `terraform apply` to update the output with the new password.
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_opensearch_user.html.markdown
> +Create a user johndoe in a opensearch database.
```suggestion
Create a user johndoe in a OpenSearch database.
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_opensearch_user.html.markdown
> +* `password_reset` - (Optional) Arbitrary string to change to trigger a password update. Use command `terraform refresh` after `terraform apply` to update output with new password.
```suggestion
* `password_reset` - (Optional) Arbitrary string to change to trigger a password update. Use the `terraform refresh` command after `terraform apply` to update the output with the new password.
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_postgresql_user.html.markdown
> +Create a user johndoe in a postgresql database.
```suggestion
Create a user johndoe in a PostgreSQL database.
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_opensearch_user.html.markdown
> +To reset password of the user previouly create, update the `password_reset` attribut.
```suggestion
-> __NOTE__ To reset password of the user previously created, update the `password_reset` attribute.
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_postgresql_user.html.markdown
> +To reset password of the user previouly create, update the `password_reset` attribut.
```suggestion
-> __NOTE__ To reset password of the user previously created, update the `password_reset` attribute.
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_postgresql_user.html.markdown
> +* `password_reset` - (Optional) Arbitrary string to change to trigger a password update. Use command `terraform refresh` after `terraform apply` to update output with new password.
```suggestion
* `password_reset` - (Optional) Arbitrary string to change to trigger a password update. Use the `terraform refresh` command after `terraform apply` to update the output with the new password.

```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_redis_user.html.markdown
> +Create a user johndoe in a redis database.
```suggestion
Create a user johndoe in a Redis database.
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_redis_user.html.markdown
> +To reset password of the user previouly create, update the `password_reset` attribut.
```suggestion
-> __NOTE__ To reset password of the user previously created, update the `password_reset` attribute.
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_redis_user.html.markdown
> +  commands	      = ["+get", "-set"]
```suggestion
  commands	  = ["+get", "-set"]
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_redis_user.html.markdown
> +  keys		        = ["data", "properties"]
```suggestion
  keys		  = ["data", "properties"]
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_redis_user.html.markdown
> +* `password_reset` - (Optional) Arbitrary string to change to trigger a password update. Use command `terraform refresh` after `terraform apply` to update output with new password.
```suggestion
* `password_reset` - (Optional) Arbitrary string to change to trigger a password update. Use the `terraform refresh` command after `terraform apply` to update the output with the new password.

```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_user.html.markdown
> +To reset password of the user previouly create, update the `password_reset` attribut.
```suggestion
-> __NOTE__ To reset password of the user previously created, update the `password_reset` attribute.
```

2022-10-05 06:25 UTC, scraly commented on website/docs/r/cloud_project_database_user.html.markdown
> +* `password_reset` - (Optional) Arbitrary string to change to trigger a password update. Use command `terraform refresh` after `terraform apply` to update output with new password.
```suggestion
* `password_reset` - (Optional) Arbitrary string to change to trigger a password update. Use the `terraform refresh` command after `terraform apply` to update the output with the new password.

```

2022-10-05 12:30 UTC, scraly approved these changes

2022-10-05 12:30 UTC, merged