Fix import of ovh_ip_reverse resources with IPv6
ovh/terraform-provider-ovh pull request #346
Opened 2022-12-14 01:48 UTC by smortex

When importing an `ovh_ip_reverse` resources, the user is expected to
provide the IP block and IP address separated with a colon, e.g.
`198.51.100.0/24:198.51.100.42`:

  * `198.51.100.0/24` is extracted as the IP block;
  * `198.51.100.42` is extracted as the address.

Unfortunately, the `:` separator does not work well with IPv6 addresses,
e.g. `2001:0DB8::/32:2001:0DB8::42` is interpreted as:

  * `2001` is extracted as the IP block;
  * `0DB8::/32:2001:0DB8::42` is extracted as the address.

This is obviously wrong and raise an API error:

```
│ Error: calling /ip/%222001/reverse/0DB8::%2F32:2001:0DB8::42:
│ 	 HTTP Error 400: "[ipReverse] Given data (0DB8::/32:2001:0DB8::42) is not valid for type ip"
```

Replace the `:` separator with a `|` separator to avoid this issue.

2022-12-15 15:54 UTC, scraly commented
Thanks for your fix.

Can you copy-paste me the `terraform import` command you tested with this fix please?

Thanks :)

2022-12-15 17:07 UTC, smortex commented
Hey @scraly !  I have some terraform definition like this that ensure each dedicated server reverse DNS for both IPv4 and IPv6 is set to `<host>.example.com` (barely readable unfortunately but I am not sure about how to improve this):

```terraform
data "ovh_dedicated_servers" "all_dedicated_servers" {}

data "ovh_dedicated_server" "dedicated_server" {
  for_each     = toset(data.ovh_dedicated_servers.all_dedicated_servers.result)
  service_name = each.key
}

resource "ovh_ip_reverse" "dedicated_server" {
  for_each = toset(data.ovh_dedicated_servers.all_dedicated_servers.result)

  ip         = "${data.ovh_dedicated_server.dedicated_server[each.key].ip}/32"
  ip_reverse = data.ovh_dedicated_server.dedicated_server[each.key].ip
  reverse    = "${split(".", data.ovh_dedicated_server.dedicated_server[each.key].name)[0]}.example.com."
}

resource "ovh_ip_reverse" "dedicated_server6" {
  for_each = toset(data.ovh_dedicated_servers.all_dedicated_servers.result)

  ip         = element([for ip in data.ovh_dedicated_server.dedicated_server[each.key].ips : ip if length(regexall("^[:[:xdigit:]]+/\\d+$", ip)) > 0], 0)
  ip_reverse = regex("^([:[:xdigit:]]+)/\\d+$", element([for ip in data.ovh_dedicated_server.dedicated_server[each.key].ips : ip if length(regexall("^[:[:xdigit:]]+/\\d+$", ip)) > 0], 0))[0]
  reverse    = "${split(".", data.ovh_dedicated_server.dedicated_server[each.key].name)[0]}.example.com."
}
```

For each server I run an import command for IPv4 and another one for IPv6:

```
terraform import 'ovh_ip_reverse.dedicated_server["ns573621.ip-51-161-116.net"]' '51.161.116.19/32|51.161.116.19'
terraform import 'ovh_ip_reverse.dedicated_server6["ns573621.ip-51-161-116.net"]' '2607:5300:203:6e13::/64|2607:5300:203:6e13::'
```

Then `terraform plan` shown me misconfigured reverse DNS entries and `terraform apply` fixed them.

2022-12-27 15:11 UTC, scraly commented
Thanks,
moreover can you add the import section in the documentation page (with the format you recommend)? Like this:
https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/cloud_project_kube#import

Thank you :)

2022-12-27 15:11 UTC, scraly requested changes
Thanks,
moreover can you add the import section in the documentation page (with the format you recommend)? Like this:
https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/cloud_project_kube#import

Thank you :)

2022-12-27 18:52 UTC, smortex commented
Example for importing an IPv6 address added.  Do you also want an example with IPv4 or is it fine this way since the syntax is basically the same?

2022-12-28 09:52 UTC, scraly commented
> Example for importing an IPv6 address added. Do you also want an example with IPv4 or is it fine this way since the syntax is basically the same?

I think only one example should be OK :)

2023-01-04 06:37 UTC, scraly commented
Any news about the example to add? :-)
I plan to create a new release in the coming days.

2023-01-04 07:33 UTC, smortex commented
Hey @scraly 

Isn't 9b8f2d2c313b52b8f9c5b56125bd1aad84e4d5d8 I added to this PR a few days ago what you are looking for?  I think this is ready for merging unless some other issue is raised :-)

Thanks!

2023-01-04 08:32 UTC, scraly commented
The status was and is still in "changes request" so I guess you didn't see my last message :-)

2023-01-04 08:35 UTC, scraly approved these changes
top, thank you :)

2023-01-04 08:36 UTC, merged