Impl Dedicated Nasha
ovh/terraform-provider-ovh pull request #349
Opened 2022-12-20 13:12 UTC by FlorianPerrot

# Description

Partial implementation NASHA resources / data with test and docs.

Thanks @goblain. Author of first implementation. see : https://github.com/ovh/terraform-provider-ovh/pull/44

## Type of change

Add Resources :
- ovh_dedicated_nasha_partition
- ovh_dedicated_nasha_partition_access
- ovh_dedicated_nasha_partition_snapshot

Add Data:
- ovh_dedicated_nasha

2022-12-27 12:58 UTC, scraly commented
Thanks :)
In every page of OVHcloud this service is called "HA-NAS" in english (or NAS-HA in french ;-) ).
So I added a suggestion of modification in all the PR (code and documentation) with this correct product name :).

2022-12-27 13:03 UTC, scraly commented on ovh/resource_dedicated_nasha_partition.go
> +			return diag.Errorf("cant parse partition id: %s", d.Id())
```suggestion
			return diag.Errorf("can't parse partition ID: %s", d.Id())
```

2022-12-27 13:03 UTC, scraly commented on ovh/resource_dedicated_nasha_partition.go
> +			return diag.Errorf("cant parse partition id: %s", d.Id())
```suggestion
			return diag.Errorf("can't parse partition ID: %s", d.Id())
```

2022-12-27 13:03 UTC, scraly commented on ovh/resource_dedicated_nasha_partition.go
> +			return diag.Errorf("cant parse partition id: %s", d.Id())
```suggestion
			return diag.Errorf("can't parse partition ID: %s", d.Id())
```

2022-12-27 13:04 UTC, scraly commented on ovh/resource_dedicated_nasha_partition.go
> +		return diag.Errorf("waiting for NASHA partition update: %s", err)
```suggestion
		return diag.Errorf("waiting for HA-NAS partition update: %s", err)
```

2022-12-27 13:04 UTC, scraly commented on ovh/resource_dedicated_nasha_partition_access.go
> +	log.Printf("[DEBUG] Created NASHA partition access")
```suggestion
	log.Printf("[DEBUG] Created HA-NAS partition access")
```

2022-12-27 13:04 UTC, scraly commented on ovh/resource_dedicated_nasha_partition_access.go
> +			return diag.Errorf("cant parse access partition id: %s", d.Id())
```suggestion
			return diag.Errorf("can't parse access partition ID: %s", d.Id())
```

2022-12-27 13:08 UTC, scraly commented on ovh/resource_dedicated_nasha_partition_snapshot.go
> +	log.Printf("[DEBUG] Created NASHA snapshot")
```suggestion
	log.Printf("[DEBUG] Created HA-NAS snapshot")
```

2022-12-27 13:08 UTC, scraly commented on ovh/resource_dedicated_nasha_test.go
> +		fmt.Printf("NASHA partition : %+v\n", partitionResponse)
```suggestion
		fmt.Printf("HA-NAS partition: %+v\n", partitionResponse)
```

2022-12-27 13:31 UTC, FlorianPerrot commented
Thanks @Scraly for review my PR.
I can replace on documentation and log message. But on "api.ovh.com" real entrypoint is called "/dedicated/nasha" to have a link between terraform resources and OVH resources i kept `dedicated_nasha`.

2022-12-27 13:43 UTC, scraly commented
Yes the name of the resource and datasource are good, because it matches with the API endpoint but I think we need to be homogeneous with the product name: https://www.ovhcloud.com/en-gb/storage-solutions/nas-ha/ :)

2022-12-27 13:49 UTC, scraly requested changes
fix `parititionName` to `partitionName`

2022-12-27 13:49 UTC, scraly commented on ovh/resource_dedicated_nasha_test.go
> +		parititionName := nashaPartitionAccessResource.Primary.Attributes["name"]
```suggestion
		partitionName := nashaPartitionAccessResource.Primary.Attributes["name"]
```

2022-12-27 13:49 UTC, scraly commented on ovh/resource_dedicated_nasha_test.go
> +		endpoint := fmt.Sprintf("/dedicated/nasha/%s/partition/%s", serviceName, parititionName)
```suggestion
		endpoint := fmt.Sprintf("/dedicated/nasha/%s/partition/%s", serviceName, partitionName)
```

2022-12-27 13:49 UTC, scraly commented on ovh/resource_dedicated_nasha_test.go
> +		endpoint := fmt.Sprintf("/dedicated/nasha/%s/partition/%s", serviceName, parititionName)
```suggestion
		endpoint := fmt.Sprintf("/dedicated/nasha/%s/partition/%s", serviceName, partitionName)
```

2022-12-27 13:49 UTC, scraly commented on ovh/resource_dedicated_nasha_test.go
> +		endpoint := fmt.Sprintf("/dedicated/nasha/%s/partition/%s", serviceName, parititionName)
```suggestion
		endpoint := fmt.Sprintf("/dedicated/nasha/%s/partition/%s", serviceName, partitionName)
```

2022-12-27 15:16 UTC, scraly commented
Thank you,
but some suggestions are not fixed for the moment :) 
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/2543381/209686387-ce694e92-af87-4433-89c7-7b75f33ddd52.png">

2022-12-27 15:27 UTC, FlorianPerrot commented
Fixed!
Sorry for this.

2022-12-28 08:40 UTC, scraly requested changes
I added some suggestions again :-) 

Moreover, the creation of resources are working :

```
$ terraform apply
data.ovh_dedicated_nasha.foo: Reading...
ovh_dedicated_nasha_partition.my-partition: Refreshing state... [id=zpool-xxxxxx/my-partition]
data.ovh_dedicated_nasha.foo: Read complete after 1s [id=zpool-xxxxxx]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # ovh_dedicated_nasha_partition_access.my-partition will be created
  + resource "ovh_dedicated_nasha_partition_access" "my-partition" {
      + id             = (known after apply)
      + ip             = "123.123.123.123/32"
      + partition_name = "my-partition"
      + service_name   = "zpool-xxxxxx"
      + type           = "readwrite"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ovh_dedicated_nasha_partition_access.my-partition: Creating...
ovh_dedicated_nasha_partition_access.my-partition: Still creating... [10s elapsed]
ovh_dedicated_nasha_partition_access.my-partition: Still creating... [20s elapsed]
ovh_dedicated_nasha_partition_access.my-partition: Still creating... [30s elapsed]
ovh_dedicated_nasha_partition_access.my-partition: Still creating... [40s elapsed]
ovh_dedicated_nasha_partition_access.my-partition: Still creating... [50s elapsed]
ovh_dedicated_nasha_partition_access.my-partition: Creation complete after 51s [id=zpool-xxxxxx/my-partition/123.123.123.123/32]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

But I have an issue when I want to "read" the partition_access :

```
$ terraform apply
data.ovh_dedicated_nasha.foo: Reading...
ovh_dedicated_nasha_partition_access.my-partition: Refreshing state... [id=zpool-xxxx/my-partition/123.123.123.123/32]
ovh_dedicated_nasha_partition.my-partition: Refreshing state... [id=zpool-xxxx/my-partition]
data.ovh_dedicated_nasha.foo: Read complete after 1s [id=zpool-xxxx]
╷
│ Error: cant parse access partition id: zpool-xxxx/my-partition/123.123.123.123/32
│
│   with ovh_dedicated_nasha_partition_access.my-partition,
│   on pr349.tf line 12, in resource "ovh_dedicated_nasha_partition_access" "my-partition":
│   12: resource "ovh_dedicated_nasha_partition_access" "my-partition" {
│
```

2022-12-28 08:40 UTC, scraly commented on website/docs/r/dedicated_nasha_partition.markdown
> +  name = "foo"
```suggestion
  name = "my-partition"
```

2022-12-28 08:40 UTC, scraly commented on website/docs/r/dedicated_nasha_partition.markdown
> +`$ terraform import ovh_dedicated_nasha_partition.foo zpool-12345/foo`
```suggestion
`$ terraform import ovh_dedicated_nasha_partition.foo zpool-12345/my-partition`
```

2022-12-28 08:40 UTC, scraly commented on website/docs/r/dedicated_nasha_partition_access.markdown
> +  protocol = "NFS"
```suggestion
  type = "readwrite"
```

2022-12-28 08:40 UTC, scraly commented on website/docs/r/dedicated_nasha_partition_access.markdown
> +  partition_name = "foo"
```suggestion
  partition_name = "my-partition"
```

2022-12-28 08:40 UTC, scraly commented on website/docs/r/dedicated_nasha_partition_access.markdown
> +resource "ovh_dedicated_nasha_partition_access" "foo" {
```suggestion
resource "ovh_dedicated_nasha_partition_access" "my-partition" {
```

2022-12-28 08:40 UTC, scraly commented on website/docs/r/dedicated_nasha_partition_access.markdown
> +  partition_name = "foo"
```suggestion
  partition_name = "my-partition"
```

2022-12-28 08:40 UTC, scraly commented on website/docs/r/dedicated_nasha_partition.markdown
> +resource "ovh_dedicated_nasha_partition" "foo" {
```suggestion
resource "ovh_dedicated_nasha_partition" "my-partition" {
```

2022-12-28 08:40 UTC, scraly commented on website/docs/r/dedicated_nasha_partition.markdown
> +* `capacity` - Reports stroage space useage in %.
```suggestion
* `capacity` - Reports storage space usage in %.
```

2022-12-28 08:40 UTC, scraly commented on website/docs/r/dedicated_nasha_partition.markdown
> +resource "ovh_dedicated_nasha_partition" "foo" {
```suggestion
resource "ovh_dedicated_nasha_partition" "my-partition" {
```

2022-12-28 08:40 UTC, scraly commented on website/docs/r/dedicated_nasha_partition_snapshot.markdown
> +  partition_name = "foo"
```suggestion
  partition_name = "my-partition"
```

2022-12-28 08:40 UTC, scraly commented on website/docs/r/dedicated_nasha_partition_snapshot.markdown
> +resource "ovh_dedicated_nasha_partition_snapshot" "foo" {
```suggestion
resource "ovh_dedicated_nasha_partition_snapshot" "my-partition" {
```

2022-12-28 08:40 UTC, scraly commented on website/docs/r/dedicated_nasha_partition_snapshot.markdown
> +* `service_name` - (Required) The internal name of your HA-NAS (it has to be ordered via OVH interface)
```suggestion
* `service_name` - (Required) The internal name of your HA-NAS (it has to be ordered via OVHcloud interface)
```

2022-12-28 08:40 UTC, scraly commented on website/docs/r/dedicated_nasha_partition_snapshot.markdown
> +* `service_name` - (Required) The internal name of your HA-NAS (it has to be ordered via OVH interface)
```suggestion
* `service_name` - (Required) The internal name of your HA-NAS (it has to be ordered via OVHcloud interface)
```

2022-12-28 08:40 UTC, scraly commented on website/docs/r/dedicated_nasha_partition_snapshot.markdown
> +`$ terraform import ovh_dedicated_nasha_partition_snapshot.foo zpool-12345/foo/day-3`
```suggestion
`$ terraform import ovh_dedicated_nasha_partition_snapshot.foo zpool-12345/my-partition/day-3`
```

2022-12-28 08:41 UTC, scraly requested changes
I added some suggestions again :-) 

Moreover, the creation of resources are working :

```
$ terraform apply
data.ovh_dedicated_nasha.foo: Reading...
ovh_dedicated_nasha_partition.my-partition: Refreshing state... [id=zpool-xxxxxx/my-partition]
data.ovh_dedicated_nasha.foo: Read complete after 1s [id=zpool-xxxxxx]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # ovh_dedicated_nasha_partition_access.my-partition will be created
  + resource "ovh_dedicated_nasha_partition_access" "my-partition" {
      + id             = (known after apply)
      + ip             = "123.123.123.123/32"
      + partition_name = "my-partition"
      + service_name   = "zpool-xxxxxx"
      + type           = "readwrite"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ovh_dedicated_nasha_partition_access.my-partition: Creating...
ovh_dedicated_nasha_partition_access.my-partition: Still creating... [10s elapsed]
ovh_dedicated_nasha_partition_access.my-partition: Still creating... [20s elapsed]
ovh_dedicated_nasha_partition_access.my-partition: Still creating... [30s elapsed]
ovh_dedicated_nasha_partition_access.my-partition: Still creating... [40s elapsed]
ovh_dedicated_nasha_partition_access.my-partition: Still creating... [50s elapsed]
ovh_dedicated_nasha_partition_access.my-partition: Creation complete after 51s [id=zpool-xxxxxx/my-partition/123.123.123.123/32]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

But I have an issue when I want to "read" the partition_access :

```
$ terraform apply
data.ovh_dedicated_nasha.foo: Reading...
ovh_dedicated_nasha_partition_access.my-partition: Refreshing state... [id=zpool-xxxx/my-partition/123.123.123.123/32]
ovh_dedicated_nasha_partition.my-partition: Refreshing state... [id=zpool-xxxx/my-partition]
data.ovh_dedicated_nasha.foo: Read complete after 1s [id=zpool-xxxx]
╷
│ Error: cant parse access partition id: zpool-xxxx/my-partition/123.123.123.123/32
│
│   with ovh_dedicated_nasha_partition_access.my-partition,
│   on pr349.tf line 12, in resource "ovh_dedicated_nasha_partition_access" "my-partition":
│   12: resource "ovh_dedicated_nasha_partition_access" "my-partition" {
│
```

2022-12-28 08:55 UTC, scraly requested changes

2022-12-28 08:55 UTC, scraly commented on ovh/resource_dedicated_nasha_partition_access.go
> +		if len(tab) != 3 {
a little fix? :-)

```suggestion
		if len(tab) != 4 {
```

2022-12-28 08:55 UTC, scraly commented on ovh/resource_dedicated_nasha_partition_access.go
> +		if len(tab) != 3 {
a little fix? :-)

```suggestion
		if len(tab) != 4 {
```

2022-12-28 09:39 UTC, FlorianPerrot commented
I fixed this issue yesterday. here: https://github.com/ovh/terraform-provider-ovh/pull/349/commits/9940526a4697f21818c972381a80364e566abd66
Can you retry your test with this fix?

Acceptance test case works for me. If I'm not mistaken, he should also work for your test.

2022-12-28 09:40 UTC, scraly requested changes

2022-12-28 09:40 UTC, scraly commented on ovh/resource_dedicated_nasha_partition_access.go
> +	ipsubnet, _ := d.Get("ip").(string)
The IP stored/read is not correct.

Indeed, when I apply an access resource:

```
ovh_dedicated_nasha_partition_access.my-partition: Creating...
ovh_dedicated_nasha_partition_access.my-partition: Still creating... [10s elapsed]
ovh_dedicated_nasha_partition_access.my-partition: Still creating... [20s elapsed]
ovh_dedicated_nasha_partition_access.my-partition: Still creating... [30s elapsed]
ovh_dedicated_nasha_partition_access.my-partition: Still creating... [40s elapsed]
ovh_dedicated_nasha_partition_access.my-partition: Still creating... [50s elapsed]
ovh_dedicated_nasha_partition_access.my-partition: Still creating... [1m0s elapsed]
ovh_dedicated_nasha_partition_access.my-partition: Creation complete after 1m1s [id=zpool-xxxx/my-partition/123.123.123.123/32]

Apply complete! Resources: 2 added, 0 changed, 1 destroyed.
```

And when I do an apply again (after solved a little the read function):

```
 $ terraform apply
data.ovh_dedicated_nasha.foo: Reading...
ovh_dedicated_nasha_partition.my-partition: Refreshing state... [id=zpool-xxxxx/my-partition]
ovh_dedicated_nasha_partition_access.my-partition: Refreshing state... [id=zpool-xxxxxxx/my-partition/123.123.123.123/32]
ovh_dedicated_nasha_partition_snapshot.my-partition: Refreshing state... [id=zpool-xxxxxx/my-partition/day-3]
data.ovh_dedicated_nasha.foo: Read complete after 1s [id=zpool-xxxxx]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # ovh_dedicated_nasha_partition_access.my-partition must be replaced
-/+ resource "ovh_dedicated_nasha_partition_access" "my-partition" {
      ~ id             = "zpool-xxxx/my-partition/123.123.123.123/32" -> (known after apply)
      ~ ip             = "123.123.123.123" -> "123.123.123.123/32" # forces replacement
        # (3 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: ^C

Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...

╷
│ Error: error asking for approval: interrupted
```

2022-12-28 09:44 UTC, scraly commented
> I fixed this issue yesterday. here: [9940526](https://github.com/ovh/terraform-provider-ovh/commit/9940526a4697f21818c972381a80364e566abd66) Can you retry your test with this fix?
> 
> Acceptance test case works for me. If I'm not mistaken, he should also work for your test.

After your fix, I have still this issue in the read access:

```
$ terraform destroy
data.ovh_dedicated_nasha.foo: Reading...
ovh_dedicated_nasha_partition_snapshot.my-partition: Refreshing state... [id=zpool-xxxxx/my-partition/day-3]
ovh_dedicated_nasha_partition_access.my-partition: Refreshing state... [id=zpool-xxxxx/my-partition/123.123.123.123/32]
ovh_dedicated_nasha_partition.my-partition: Refreshing state... [id=zpool-xxxxx/my-partition]
data.ovh_dedicated_nasha.foo: Read complete after 0s [id=zpool-xxxxx]
╷
│ Error: can't parse access partition ID: zpool-xxxxx/my-partition/123.123.123.123/32
│
│   with ovh_dedicated_nasha_partition_access.my-partition,
│   on pr349.tf line 12, in resource "ovh_dedicated_nasha_partition_access" "my-partition":
│   12: resource "ovh_dedicated_nasha_partition_access" "my-partition" {
│
```

2022-12-28 10:02 UTC, FlorianPerrot commented
You should retry without context. In your case the access resource have a bad ID, generated before my fix.

2022-12-28 12:58 UTC, scraly requested changes
Tests are now Ok for me :-)

So please look at every suggestions have done and commit them.
Thank you

2022-12-28 12:58 UTC, scraly commented on website/docs/d/dedicated_nasha.html.markdown
> +data "ovh_dedicated_nasha" "foo" {
```suggestion
data "ovh_dedicated_nasha" "my-nas-ha" {
```

2022-12-28 12:58 UTC, scraly commented on website/docs/r/dedicated_nasha_partition.markdown
> +`$ terraform import ovh_dedicated_nasha_partition.foo zpool-12345/my-partition`
```suggestion
`$ terraform import ovh_dedicated_nasha_partition.my-partition zpool-12345/my-partition`
```

2022-12-28 12:58 UTC, scraly commented on website/docs/r/dedicated_nasha_partition.markdown
> +`$ terraform import ovh_dedicated_nasha_partition.foo zpool-12345/my-partition`
```suggestion
`$ terraform import ovh_dedicated_nasha_partition.my-partition zpool-12345/my-partition`
```

2022-12-28 12:58 UTC, scraly commented on website/docs/r/dedicated_nasha_partition_access.markdown
> +`$ terraform import ovh_dedicated_nasha_partition_access.foo zpool-12345/my-partition/123.123.123.123%2F32`
```suggestion
`$ terraform import ovh_dedicated_nasha_partition_access.my-partition zpool-12345/my-partition/123.123.123.123%2F32`
```

2022-12-28 12:58 UTC, scraly commented on website/docs/r/dedicated_nasha_partition_snapshot.markdown
> +`$ terraform import ovh_dedicated_nasha_partition_snapshot.foo zpool-12345/my-partition/day-3`
```suggestion
`$ terraform import ovh_dedicated_nasha_partition_snapshot.my-partition zpool-12345/my-partition/day-3`
```

2022-12-28 15:31 UTC, scraly approved these changes

2022-12-28 15:31 UTC, scraly commented
Good new feature, it's OK for me :)

2022-12-28 15:32 UTC, merged