Clarify cloud project import
ovh/terraform-provider-ovh pull request #361
Opened 2023-01-17 14:30 UTC by yomovh

Clarify documentation based on issue https://github.com/ovh/terraform-provider-ovh/issues/342

2023-01-17 14:31 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1283.0 ✔ 
* 
  * checks ✔

2023-01-17 14:31 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1282.0 ✔ 
* 
  * checks ✔

2023-01-17 14:36 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1283.0 ✘  
* 
  * checks ✘

2023-01-17 14:41 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1282.0 ✘  
* 
  * checks ✘

2023-01-18 13:14 UTC, scraly requested changes
Thanks for the PR :-) 

I added two fixes/suggestions.

Moreover, I see the list of attributes are not up to date, is it possible to update the list?

Example of actual attributes:

```
resource "ovh_cloud_project" "my_cloud_project" {
    access       = "full"
    description  = "MY_PROJECT"
    id           = "123456789"
    order        = [
        {
            date            = "2021-09-20T15:14:37+02:00"
            details         = [
                {
                    description     = "Activation d'un projet /cloud"
                    domain          = "xxxx"
                    order_detail_id = 123456789
                    quantity        = "1"
                },
                {
                    description     = "Public Cloud Project cloud project prices jusqu'au 01/10/2021"
                    domain          = "xxxxx"
                    order_detail_id = 123456789
                    quantity        = "1"
                },
            ]
            expiration_date = "2021-10-04T23:29:59+02:00"
            order_id        = 123456789
        },
    ]
    project_id   = "xxxxx"
    project_name = "xxx"
    status       = "ok"
}
```

And another question, I see in the doc a warning: "This resource is in beta state. Use with caution."

Can you see if this warning block can be remove now? :) 

Thanks

2023-01-18 13:14 UTC, scraly commented on website/docs/r/cloud_project.html.markdown
> +$ terraform import ovh_cloud_project_database.my_cloud_project order_id
```suggestion
$ terraform import ovh_cloud_project.my_cloud_project order_id
```

2023-01-18 13:14 UTC, scraly commented on website/docs/r/cloud_project.html.markdown
> +Cloud project can be imported using the `order_id` that can be retrieved in the [order page](https://www.ovh.com/manager/#/dedicated/billing/orders/orders) at the creation time of the public cloud pr
```suggestion
Cloud project can be imported using the `order_id` that can be retrieved in the [order page](https://www.ovh.com/manager/#/dedicated/billing/orders/orders) at the creation time of the Public Cloud project. 
```

2023-01-18 16:21 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1288.0 ✔ 
* 
  * checks ✔

2023-01-18 16:21 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1287.0 ✔ 
* 
  * checks ✔

2023-01-18 16:25 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1288.0 ✘  
* 
  * checks ✘

2023-01-18 16:39 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1287.0 ✘  
* 
  * checks ✘

2023-01-18 16:51 UTC, yomovh commented
Attributes added.

2023-01-18 16:52 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1290.0 ✔ 
* 
  * checks ✔

2023-01-18 16:53 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1289.0 ✔ 
* 
  * checks ✔

2023-01-18 16:59 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1290.0 ✘  
* 
  * checks ✘

2023-01-18 17:02 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1289.0 ✘  
* 
  * checks ✘

2023-01-23 13:48 UTC, scraly commented
Thanks :)

2023-01-23 13:49 UTC, merged