fix(dbaas-logs): input tests
ovh/terraform-provider-ovh pull request #366
Opened 2023-01-24 16:09 UTC by pdepaepe

ref: #OB-4901

Hello,

This PR fix a missing parameter (serviceName) on tests to handle the new endpoint as described here: https://github.com/ovh/terraform-provider-ovh/pull/347

As always, thanks for your time on this.

Signed-off-by: Pierre De Paepe <pierre.de-paepe@ovhcloud.com>

2023-01-24 16:15 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1311.0 ✘  
* 
  * checks ✘

2023-01-25 09:18 UTC, yanndegat approved these changes

2023-02-08 10:47 UTC, scraly requested changes

2023-02-08 10:47 UTC, scraly commented on ovh/resource_dbaas_logs_input_test.go
> +	version := "7.x"
I think it should be useful to put in environment variable the version, if not at each version deprecation or removal, this test should be updated

2023-02-10 12:56 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1371.0 ✔ 
* 
  * checks ✔

2023-02-10 12:56 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1370.0 ✔ 
* 
  * checks ✔

2023-02-10 13:23 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1371.0 ✔ 
* 
  * checks ✔

2023-02-10 13:23 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1371.0 ■

2023-02-10 13:23 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1371.0 ■

2023-02-10 13:23 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1370.0 ✔ 
* 
  * checks ✔

2023-02-10 13:23 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1370.0 ■   
* 
  * checks ■

2023-02-10 13:23 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1370.0 ■   
* 
  * checks ■

2023-02-10 14:57 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1372.0 ✔ 
* 
  * checks ✔

2023-02-10 14:57 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1373.0 ✔ 
* 
  * checks ✔

2023-02-10 15:01 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1372.0 ✘  
* 
  * checks ✘

2023-02-10 15:26 UTC, scraly approved these changes

2023-02-10 15:27 UTC, merged