Add subcategory in documentation page
ovh/terraform-provider-ovh pull request #400
Opened 2023-03-20 09:32 UTC by yomovh

# Description
In order to group the resources / data source of the documentation page on the registry of Hashicorp : https://registry.terraform.io/providers/ovh/ovh/latest/docs

I have added a [subcategory](https://developer.hashicorp.com/terraform/registry/providers/docs#subcategories) in the YAMLFrontmatter of the documentation files. I have also removed the other attributes which were not useful and not  rendered in the Terraform Registry web UI (see [here](https://developer.hashicorp.com/terraform/registry/providers/docs#yaml-frontmatter))

The category naming are the official ones, courtesy of the product map repository https://github.com/baaastijn/ovh_product_map

## Type of change

- [x] Documentation update

# How Has This Been Tested?
Not applicable

# Checklist:
Not applicable

2023-03-20 14:11 UTC, scraly requested changes
Thanks  :) 
The only suggestion I have is to add in he readme or in the contributing md file that the list of exising subcategory are in https://www.product-map.ovh/ website :-)

2023-03-20 17:04 UTC, yomovh commented
Done ;-)

2023-03-20 17:05 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1532.0 ✔ 
* 
  * checks ✔

2023-03-20 17:05 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1533.0 ✔ 
* 
  * checks ✔

2023-03-21 08:08 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1532.0 ✘  
* 
  * checks ✘

2023-03-21 08:09 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1533.0 ✘  
* 
  * checks ✘

2023-03-21 08:19 UTC, scraly requested changes

2023-03-21 08:19 UTC, scraly commented on CONTRIBUTING.md
> +- When adding a documentation page, use the `subcategory:` tag in the [YAML Frontmatter](https://developer.hashicorp.com/terraform/registry/providers/docs#yaml-frontmatter) with a value equals to the
```suggestion
- When adding a documentation page, use the `subcategory:` tag in the [YAML Frontmatter](https://developer.hashicorp.com/terraform/registry/providers/docs#yaml-frontmatter) with a value equals to the product name defined in the OVHcloud [product map](https://www.product-map.ovh/)
```

2023-03-21 08:25 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1536.0 ✔ 
* 
  * checks ✔

2023-03-21 08:25 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1535.0 ✔ 
* 
  * checks ✔

2023-03-21 08:26 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1536.0 ✘  
* 
  * checks ✘

2023-03-21 08:26 UTC, scraly approved these changes

2023-03-21 08:26 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1535.0 ✘  
* 
  * checks ✘

2023-03-21 08:28 UTC, merged