feat: support identity groups
ovh/terraform-provider-ovh pull request #420
Opened 2023-05-22 07:24 UTC by fehrnah

This add handling of iam identity groups.

It is *heavily* inspired by the identity datasource/provider.

## Type of change

Please delete options that are not relevant.

- [x ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A: `make testacc TESTARGS="-run TestAccMeIdentity.*"`

**Test Configuration**:
* Terraform version: `terraform version`: Terraform v1.4.6

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or issues
- [x] I have added acceptance tests that prove my fix is effective or that my feature works
- [x] New and existing acceptance tests pass locally with my changes
- [] I ran successfully `go mod vendor` if I added or modify `go.mod` file

2023-05-22 07:57 UTC, Stoakes commented on website/docs/d/me_identity_group.markdown
> +* `last_update` - Last update of this group.
```suggestion
* `last_update` - Date of the last update of this group.
```

2023-05-22 08:01 UTC, Stoakes commented on website/docs/d/me_identity_groups.markdown
> +* `groups` - The list of the group names of all the identity groups.
```suggestion
* `groups` - List of names of every identity groups.
```

2023-05-23 07:44 UTC, scraly requested changes

2023-05-23 07:44 UTC, scraly commented on website/docs/d/me_identity_group.markdown
> +  group = "my_group_name"
```suggestion
  name = "my_group_name"
```

2023-05-23 13:07 UTC, scraly requested changes

2023-05-24 08:39 UTC, scraly approved these changes

2023-05-24 08:59 UTC, merged