Add import documentation on iplb resources
ovh/terraform-provider-ovh pull request #432
Opened 2023-06-15 16:15 UTC by yomovh

# Description

Add documentation on the import of iplb resources (farm, server, route, rule)

Fixes #429 

## Type of change
- [ X] Documentation update

# How Has This Been Tested?
N/A

2023-06-19 09:47 UTC, scraly requested changes

2023-06-19 09:47 UTC, scraly commented on website/docs/r/iploadbalancing_http_route.html.markdown
> +HTTP route  can be imported using the following format `service_name` and the `id` of the route separated by "/" e.g.
```suggestion
HTTP route can be imported using the following format `service_name` and the `id` of the route separated by "/" e.g.
```

2023-06-19 09:47 UTC, scraly commented on website/docs/r/iploadbalancing_http_farm.html.markdown
> +HTTP Farm can be imported using the following format `service_name` and the `id` of the farm, separated by "/" e.g.
```suggestion
HTTP farm can be imported using the following format `service_name` and the `id` of the farm, separated by "/" e.g.
```

2023-06-19 09:47 UTC, scraly commented on website/docs/r/iploadbalancing_http_farm_server.html.markdown
> +HTTP farm server can be imported using the following format `service_name`,  the `id` of the farm and the `id` of the server separated by "/" e.g.
```suggestion
HTTP farm server can be imported using the following format `service_name`, the `id` of the farm and the `id` of the server separated by "/" e.g.
```

2023-06-19 09:47 UTC, scraly commented on website/docs/r/iploadbalancing_http_route_rule.html.markdown
> +HTTP route rule can be imported using the following format `service_name`,  the `id` of the route and the `id` of the rule separated by "/" e.g.
```suggestion
HTTP route rule can be imported using the following format `service_name`, the `id` of the route and the `id` of the rule separated by "/" e.g.
```

2023-06-19 09:47 UTC, scraly commented on website/docs/r/iploadbalancing_tcp_farm_server.html.markdown
> +TCP farm server can be imported using the following format `service_name`,  the `id` of the farm and the `id` of the server separated by "/" e.g.
```suggestion
TCP farm server can be imported using the following format `service_name`, the `id` of the farm and the `id` of the server separated by "/" e.g.
```

2023-06-19 09:47 UTC, scraly commented on website/docs/r/iploadbalancing_tcp_route.html.markdown
> +TCP route  can be imported using the following format `service_name` and the `id` of the route separated by "/" e.g.
```suggestion
TCP route can be imported using the following format `service_name` and the `id` of the route separated by "/" e.g.
```

2023-06-19 09:47 UTC, scraly commented on website/docs/r/iploadbalancing_tcp_route_rule.html.markdown
> +TCP route rule can be imported using the following format `service_name`,  the `id` of the route and the `id` of the rule separated by "/" e.g.
```suggestion
TCP route rule can be imported using the following format `service_name`, the `id` of the route and the `id` of the rule separated by "/" e.g.
```

2023-06-21 12:49 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1806.0 ✔ 
* 
  * checks ✔

2023-06-21 12:50 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1805.0 ✔ 
* 
  * checks ✔

2023-06-21 15:08 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-check#1806.0 ✔ 
* 
  * checks ✔

2023-06-21 15:08 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1806.0 ■

2023-06-21 15:08 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1805.0 ■

2023-06-21 15:08 UTC, ovh-cds commented
CDS Report terraform-provider-ovh-testacc#1805.0 ■

2023-08-18 09:10 UTC, scraly approved these changes

2023-08-18 09:11 UTC, merged

2023-08-18 09:11 UTC, scraly commented
Thanks :)