Use catalog_name if defined
ovh/terraform-provider-ovh pull request #436
Opened 2023-06-26 13:06 UTC by bchaillou-ovh

# Description

This PR is a request from Webhosting Infra team:
- Add catalog_name on order_cart (for OptionsPlan). Unit tests updated.

## Type of change

Please delete options that are not relevant.
- [X] Improvement (improve existing resource(s) or datasource(s))

# How Has This Been Tested?
Run unit tests.

2023-08-18 13:45 UTC, scraly requested changes
Can you add a working example with a "catalog_name" in the documentation?

2023-08-29 09:27 UTC, bchaillou-ovh commented
Example updated with catalog_name.

2023-09-01 10:44 UTC, scraly requested changes
Acceptance tests fails 

```
$ make testacc TESTARGS="-run TestAccDataSourceOrderCartIpLoadbalancingOptionsPlan_basic"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccDataSourceOrderCartIpLoadbalancingOptionsPlan_basic -timeout 600m -p 10
?   	github.com/ovh/terraform-provider-ovh	[no test files]
?   	github.com/ovh/terraform-provider-ovh/ovh/helpers	[no test files]
=== RUN   TestAccDataSourceOrderCartIpLoadbalancingOptionsPlan_basic
    data_order_cart_product_options_plan_test.go:64: Step 1/1 error: Error running pre-apply refresh: exit status 1

        Error: Error calling Get /order/cart/xxxxxxxxxx/ipLoadbalancing/options?planCode=iplb-mutu&catalogName=iplb_private_beta:
        	 "OVHcloud API error (status code 400): Client::BadRequest: \"Cart needs to be assigned to specify a catalog name\" (X-OVH-Query-Id: EU.ext-xxxxxxxxxxxxxxxxxxxxxxx)"

          with data.ovh_order_cart_product_options_plan.plan,
          on terraform_plugin_test.tf line 8, in data "ovh_order_cart_product_options_plan" "plan":
           8: data "ovh_order_cart_product_options_plan" "plan" {

--- FAIL: TestAccDataSourceOrderCartIpLoadbalancingOptionsPlan_basic (26.94s)
FAIL
FAIL	github.com/ovh/terraform-provider-ovh/ovh	27.433s
testing: warning: no tests to run
PASS
ok  	github.com/ovh/terraform-provider-ovh/ovh/helpers/hashcode	0.260s [no tests to run]
FAIL
make: *** [testacc] Error 1
```

and

```
$ make testacc TESTARGS="-run TestAccDataSourceOrderCartIpLoadbalancingPlan_basic"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccDataSourceOrderCartIpLoadbalancingPlan_basic -timeout 600m -p 10
?   	github.com/ovh/terraform-provider-ovh	[no test files]
?   	github.com/ovh/terraform-provider-ovh/ovh/helpers	[no test files]
=== RUN   TestAccDataSourceOrderCartIpLoadbalancingPlan_basic
    data_order_cart_product_plan_test.go:44: Step 1/1 error: Error running pre-apply refresh: exit status 1

        Error: Error calling Get /order/cart/xxxxxxx/ipLoadbalancing?catalogName=iplb_private_beta:
        	 "OVHcloud API error (status code 400): Client::BadRequest: \"Cart needs to be assigned to specify a catalog name\" (X-OVH-Query-Id: EU.ext-xxxxxxxxxxxx)"

          with data.ovh_order_cart_product_plan.plan,
          on terraform_plugin_test.tf line 8, in data "ovh_order_cart_product_plan" "plan":
           8: data "ovh_order_cart_product_plan" "plan" {

--- FAIL: TestAccDataSourceOrderCartIpLoadbalancingPlan_basic (17.42s)
FAIL
FAIL	github.com/ovh/terraform-provider-ovh/ovh	17.840s
testing: warning: no tests to run
PASS
ok  	github.com/ovh/terraform-provider-ovh/ovh/helpers/hashcode	0.241s [no tests to run]
FAIL
make: *** [testacc] Error 1
```

2023-11-20 10:10 UTC, amstuta requested changes

2023-11-20 10:10 UTC, amstuta commented on website/docs/d/order_cart_product_options_plan.html.markdown
> +* `catalog_name` - Catalog name (Internal API - restricted to OVHcloud internal employees)
It is not acceptable to add parameters that are restricted to OVHcloud employees on the public provider. You should check internally with the team responsible for these routes if it's possible to make this parameter public and then we will check this PR.

2024-03-15 16:42 UTC, amstuta commented
Closing this request for inactivity, don't hesitate to re-open it if `catalog_name` field goes public.

2024-03-15 16:42 UTC, closed without merging