Implement /move route
ovh/terraform-provider-ovh pull request #437
Opened 2023-06-26 13:07 UTC by bchaillou-ovh

# Description

This PR is a request from Webhosting Infra team:
- Add /move endpoint. Unit tests added.

## Type of change

- [X] Improvement (improve existing resource(s) or datasource(s))

# How Has This Been Tested?
Run unit tests.

2023-08-18 13:38 UTC, scraly requested changes
When you create resources and/or datasources, please create associated documentation pages.

2023-09-01 12:39 UTC, scraly requested changes
Several typos found + please list acceptance tests to run and test them please :)

2023-09-01 12:39 UTC, scraly commented on website/docs/d/iploadbalancing_failover_ip_attach_html.markdown
> +# ovh_iploadbalancing_vrack_network (Data Source)
What is the correct name of the documetation page? :-) 

"ovh_iploadbalancing_failover_ip_attach" ? ;-)

2023-09-01 12:39 UTC, scraly commented on website/docs/d/iploadbalancing_failover_ip_attach_html.markdown
> +data ovh_iploadbalancing_failover_ip_attach failoverip {
```suggestion
data "ovh_iploadbalancing_failover_ip_attach" "failoverip" {
```

2023-09-01 12:39 UTC, scraly commented on website/docs/r/iploadbalancing_failover_ip_attach.html.markdown
> +# ovh\_iploadbalancing\_failover\_ip\_attach
```suggestion
# ovh_iploadbalancing_failover_ip_attach
```

2023-09-01 12:39 UTC, scraly commented on website/docs/r/iploadbalancing_failover_ip_attach.html.markdown
> +resource ovh_iploadbalancing_failover_ip_attach failoverip {
```suggestion
resource "ovh_iploadbalancing_failover_ip_attach" "failoverip" {
```

2023-09-01 12:39 UTC, scraly commented on website/docs/r/iploadbalancing_failover_ip_attach.html.markdown
> +* `to` - (Required) Service distination
```suggestion
* `to` - (Required) Service destination
```

2023-09-01 12:39 UTC, scraly commented on website/docs/d/iploadbalancing_failover_ip_attach_html.markdown
> +Use this data source to get list failover ip routed for your IPLoadbalancer associated with your OVHcloud account.
```suggestion
Use this data source to list all failover IP routed to this IPLB.
```

2023-11-20 16:35 UTC, amstuta requested changes

2023-11-20 16:35 UTC, amstuta commented on ovh/types_iploadbalancing.go
> +	Destination string       `json:"destination"`
from what I see in the API schemas here: https://api.ovh.com/console-preview/?section=%2Fip&branch=v1#post-/ip/-ip-/move
the field `destination` is an object containing a `serviceName` field

2023-11-20 16:35 UTC, amstuta commented on ovh/types_iploadbalancing.go
> +	Function    string       `json:"function"`
you should declare a const for this ike you did with `IpTaskStatus`

2023-11-20 16:35 UTC, amstuta commented on ovh/types_iploadbalancing.go
> +	Nexthop string `json:"nexthop"`
```suggestion
	Nexthop string `json:"nexthop,omitempty"`
```

2024-03-15 16:46 UTC, amstuta commented
Closing this PR for inactivity, don't hesitate to re-open it if still needed.

2024-03-15 16:46 UTC, closed without merging