Request cluster_id and service_name for a dbaas_logs_cluster resource…
ovh/terraform-provider-ovh pull request #446
Opened 2023-07-24 13:36 UTC by vaxvms

…/data

You can have more than one cluster_id per service_name

# Description

Instead on blindly selecting the first cluster_id of a service_name in dbaas_logs_cluster resource and data, request the user to give it.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (improve existing resource(s) or datasource(s))
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A: `make testacc TESTARGS="-run TestAccDataSourceXxxxYyyyZzzzz_basic"`
- [ ] Test B: `make testacc TESTARGS="-run TestAccDataSourceXxxxYyyyZzzzz_basic"`

**Test Configuration**:
* Terraform version: `terraform version`: Terraform vx.y.z
* Existing HCL configuration you used: 
```hcl
resource "" "" {
 xx = "yy"
 zz = "aa"
}
```

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings or issues
- [ ] I have added acceptance tests that prove my fix is effective or that my feature works
- [ ] New and existing acceptance tests pass locally with my changes
- [ ] I ran succesfully `go mod vendor` if I added or modify `go.mod` file

2023-08-30 12:58 UTC, vaxvms commented
You're right, it's done

2023-11-17 15:01 UTC, amstuta commented on ovh/data_dbaas_logs_clusters_test.go
> +				Check: resource.ComposeTestCheckFunc(
do you really need these two steps ?
I think you could have only one step with the following check:
```go
Check: resource.ComposeTestCheckFunc(
	resource.TestCheckResourceAttr(
		"data.ovh_dbaas_logs_clusters.ldp",
		"service_name",
		serviceName,
	),
	resource.TestCheckTypeSetElemAttr(
		"data.ovh_dbaas_logs_clusters.ldp",
		"uuids.*",
		clusterId,
	),
),
```

2023-11-20 09:07 UTC, vaxvms commented on ovh/data_dbaas_logs_cluster.go
> +	d.SetId(clusterId)
Other dbaas_logs resources don't use a composite of serviceName + id. I'll check with LDP team

2023-11-20 09:24 UTC, amstuta commented on ovh/data_dbaas_logs_cluster.go
> +	d.SetId(clusterId)
I don't know if that's possible, but if a cluster is used by several LDP services, you will end up with two resources having the same ID. IMO we should use both service name and clusterId to make sure we won't ever have conflicts.

2023-11-23 15:01 UTC, vaxvms commented
- id of dbaas_logs_cluster is now a concatenation of service name and cluster id. It will break existing usage.
- if cluster id isn't provided, the cluster_id of the default cluster is used

2023-12-08 17:30 UTC, rbeuque74 commented on ovh/data_dbaas_logs_cluster.go
> +	d.SetId(clusterId)
```suggestion
	d.SetId(serviceName+"_"+clusterId)
```

2023-12-08 17:38 UTC, rbeuque74 requested changes
Just this one comment, and we will be good :)

2023-12-13 18:14 UTC, rbeuque74 approved these changes

2023-12-13 18:15 UTC, merged

2023-12-13 18:15 UTC, rbeuque74 commented
Thanks for your contribution