Add Database kafka schema registry
ovh/terraform-provider-ovh pull request #449
Opened 2023-07-31 15:50 UTC by BellionBastien

# Description

Adding resource and datasource  for newly implemented schema registry ACL on kafka databases.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A: `make testacc TESTARGS="-run TestAccCloudProjectDatabaseKafkaSchemaregistryacl_basic"`
- [ ] Test B: `make testacc TESTARGS="-run TestAccCloudProjectDatabaseKafkaSchemaregistryaclsDataSource_basic"`

```

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings or issues
- [ ] I have added acceptance tests that prove my fix is effective or that my feature works
- [ ] New and existing acceptance tests pass locally with my changes
- [ ] I ran succesfully `go mod vendor` if I added or modify `go.mod` file

2023-08-08 08:58 UTC, lpatte approved these changes

2023-08-18 09:46 UTC, scraly requested changes
The new feature is working, thanks! :-) 

Just some remarks, typos and few changes requested.

2023-08-18 09:46 UTC, scraly commented on website/docs/r/cloud_project_database_kafka_schemaregistryacl.html.markdown
> +Creates a schema registry ACL for a kafka cluster associated with a public cloud project.
```suggestion
Creates a schema registry ACL for a Kafka cluster associated with a public cloud project.
```

2023-08-18 09:46 UTC, scraly commented on website/docs/r/cloud_project_database_kafka_schemaregistryacl.html.markdown
> +OVHcloud Managed kafka clusters schema registry ACLs can be imported using the `service_name`, `cluster_id` and `id` of the schema registry acl, separated by "/" E.g.,
```suggestion
OVHcloud Managed Kafka clusters schema registry ACLs can be imported using the `service_name`, `cluster_id` and `id` of the schema registry ACL, separated by "/" E.g.,
```

2023-08-18 09:46 UTC, scraly commented on ovh/data_cloud_project_database_kafka_schemaregistryacl.go
> +				Description: "Resource affected by this acl",
```suggestion
				Description: "Resource affected by this ACL",
```

2023-08-18 09:46 UTC, scraly commented on ovh/data_cloud_project_database_kafka_schemaregistryacl.go
> +				Description: "Username affected by this acl",
```suggestion
				Description: "Username affected by this ACL",
```

2023-08-18 09:46 UTC, scraly commented on ovh/data_cloud_project_database_kafka_schemaregistryacl.go
> +	log.Printf("[DEBUG] Read acl %+v", res)
```suggestion
	log.Printf("[DEBUG] Read ACL %+v", res)
```

2023-08-18 09:46 UTC, scraly commented on ovh/data_cloud_project_database_kafka_schemaregistryacls.go
> +	log.Printf("[DEBUG] Will read schema registry acls from cluster %s from project %s", clusterId, serviceName)
```suggestion
	log.Printf("[DEBUG] Will read schema registry ACLs from cluster %s from project %s", clusterId, serviceName)
```

2023-08-18 09:46 UTC, scraly commented on ovh/data_cloud_project_database_kafka_schemaregistryacls.go
> +				Description: "List of schema registry acl ids",
```suggestion
				Description: "List of schema registry ACL IDs",
```

2023-08-18 09:46 UTC, scraly commented on ovh/resource_cloud_project_database_kafka_schemaregistryacl.go
> +				Description: "Resource affected by this acl",
```suggestion
				Description: "Resource affected by this ACL",
```

2023-08-18 09:46 UTC, scraly commented on ovh/resource_cloud_project_database_kafka_schemaregistryacl.go
> +				Description: "Username affected by this acl",
```suggestion
				Description: "Username affected by this ACL",
```

2023-08-18 09:46 UTC, scraly commented on ovh/resource_cloud_project_database_kafka_schemaregistryacl.go
> +	log.Printf("[DEBUG] Will create schema registry acl: %+v for cluster %s from project %s", params, clusterId, serviceName)
```suggestion
	log.Printf("[DEBUG] Will create schema registry ACL: %+v for cluster %s from project %s", params, clusterId, serviceName)
```

2023-08-18 09:46 UTC, scraly commented on ovh/resource_cloud_project_database_kafka_schemaregistryacl.go
> +	log.Printf("[DEBUG] Waiting for schema registry acl %s to be READY", res.Id)
```suggestion
	log.Printf("[DEBUG] Waiting for schema registry ACL %s to be READY", res.Id)
```

2023-08-18 09:46 UTC, scraly commented on ovh/resource_cloud_project_database_kafka_schemaregistryacl.go
> +	log.Printf("[DEBUG] schema registry acl %s is READY", res.Id)
```suggestion
	log.Printf("[DEBUG] schema registry ACL %s is READY", res.Id)
```

2023-08-18 09:46 UTC, scraly commented on ovh/resource_cloud_project_database_kafka_schemaregistryacl.go
> +	log.Printf("[DEBUG] Will read schema registry acl %s from cluster %s from project %s", id, clusterId, serviceName)
```suggestion
	log.Printf("[DEBUG] Will read schema registry ACL %s from cluster %s from project %s", id, clusterId, serviceName)
```

2023-08-18 09:46 UTC, scraly commented on ovh/resource_cloud_project_database_kafka_schemaregistryacl.go
> +	log.Printf("[DEBUG] Will delete schema registry acl  %s from cluster %s from project %s", id, clusterId, serviceName)
```suggestion
	log.Printf("[DEBUG] Will delete schema registry ACL %s from cluster %s from project %s", id, clusterId, serviceName)
```

2023-08-18 09:46 UTC, scraly commented on ovh/resource_cloud_project_database_kafka_schemaregistryacl.go
> +	log.Printf("[DEBUG] Waiting for schema registry acl %s to be DELETED", id)
```suggestion
	log.Printf("[DEBUG] Waiting for schema registry ACL %s to be DELETED", id)
```

2023-08-18 09:46 UTC, scraly commented on ovh/resource_cloud_project_database_kafka_schemaregistryacl.go
> +	log.Printf("[DEBUG] schema registry acl %s is DELETED", id)
```suggestion
	log.Printf("[DEBUG] schema registry ACL %s is DELETED", id)
```

2023-08-18 09:46 UTC, scraly commented on ovh/resource_cloud_project_database_kafka_schemaregistryacl.go
> +		return diag.Errorf("timeout while waiting schema registry acl %s to be DELETED: %s", id, err.Error())
```suggestion
		return diag.Errorf("timeout while waiting schema registry ACL %s to be DELETED: %s", id, err.Error())
```

2023-08-18 09:46 UTC, scraly commented on ovh/data_cloud_project_database_kafka_schemaregistryacl.go
> +				Description: "Shema registry acl ID",
```suggestion
				Description: "Shema registry ACL ID",
```

2023-08-18 09:46 UTC, scraly commented on ovh/data_cloud_project_database_kafka_schemaregistryacl.go
> +	log.Printf("[DEBUG] Will read schema registry acl %s from cluster %s from project %s", id, clusterID, serviceName)
```suggestion
	log.Printf("[DEBUG] Will read schema registry ACL %s from cluster %s from project %s", id, clusterID, serviceName)
```

2023-08-18 09:46 UTC, scraly commented on ovh/resource_cloud_project_database_kafka_schemaregistryacl.go
> +		return diag.Errorf("timeout while waiting schema registry acl %s to be READY: %s", res.Id, err.Error())
```suggestion
		return diag.Errorf("timeout while waiting schema registry ACL %s to be READY: %s", res.Id, err.Error())
```

2023-08-18 09:46 UTC, scraly commented on ovh/resource_cloud_project_database_kafka_schemaregistryacl.go
> +	log.Printf("[DEBUG] Read schema registry acl %+v", res)
```suggestion
	log.Printf("[DEBUG] Read schema registry ACL %+v", res)
```

2023-08-18 12:30 UTC, merged