WIP : fix(cloudProject): creation and import for cloudProject in the US
ovh/terraform-provider-ovh pull request #455
Opened 2023-08-24 20:00 UTC by Stoakes

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #xx (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (improve existing resource(s) or datasource(s))
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A: `make testacc TESTARGS="-run TestAccDataSourceXxxxYyyyZzzzz_basic"`
- [ ] Test B: `make testacc TESTARGS="-run TestAccDataSourceXxxxYyyyZzzzz_basic"`

**Test Configuration**:
* Terraform version: `terraform version`: Terraform vx.y.z
* Existing HCL configuration you used: 
```hcl
resource "" "" {
 xx = "yy"
 zz = "aa"
}
```

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings or issues
- [ ] I have added acceptance tests that prove my fix is effective or that my feature works
- [ ] New and existing acceptance tests pass locally with my changes
- [ ] I ran succesfully `go mod vendor` if I added or modify `go.mod` file

2023-08-28 12:44 UTC, scraly requested changes

2023-08-28 12:44 UTC, scraly commented on website/docs/r/cloud_project.html.markdown
> +  * `plan_code` - (Required) Plan code. This value must be adapted depending on your `OVH_ENDPOINT` value. It's `project.2018` for `ovh-{eu,ca}` and `project` when using `ovh-us`.`
```suggestion
  * `plan_code` - (Required) Plan code. This value must be adapted depending on your `OVH_ENDPOINT` value. It's `project.2018` for `ovh-{eu,ca}` and `project` when using `ovh-us`.
```

2023-08-31 14:17 UTC, Stoakes commented
Hello, 

Is there anything missing on this PR ? Or can we merge it ?

2023-08-31 14:24 UTC, scraly commented
We are waiting for an US account in order to test everything as the user will do.

2023-09-06 16:38 UTC, Stoakes commented
Creation of public cloud project patched.

The deletion (and update) of a public cloud project in the US is not working yet because `/me/notification/email/history` (used for project confirmation deletion) is not available in the US.

@yomovh & myself will see how we deal with it.

2023-09-07 11:49 UTC, Stoakes commented
We don't want to put too much US specific logic in the provider and will work into getting resources ordered through `/order` deletable in the US.

So for now, as agreed with  @yomovh, I added a notice about the known issue that a public cloud project cannot be deleted in the US through Terraform.

2023-09-07 14:05 UTC, yomovh approved these changes
Thanks for your PR

2023-09-11 07:27 UTC, scraly approved these changes

2023-09-11 07:30 UTC, scraly commented
After all the things we saw, edited and fixed, now, the PR is good for me 💪

2023-09-11 07:30 UTC, merged