Improve error message : add request ID
ovh/terraform-provider-ovh pull request #615
Opened 2024-04-11 08:15 UTC by theredcat

# Description

Add request ID in error message when CheckDeleted function is used. This information is systematically asked by the support but isn't available anywhere in a normal run

## Type of change

-  Improvement (improve existing resource(s) or datasource(s))

# How Has This Been Tested?

Just waited for one of the occasionnal API fail

2024-04-11 12:02 UTC, amstuta commented on ovh/helpers/helpers.go
> +	return fmt.Errorf("calling %s:\n\t %s Query ID : %s", endpoint, err.Error(), errOvh.QueryID)
you should use `errOvh.QueryID` only if we're sure that `ok` is true, something like:
```
var queryID string
if ok {
  queryID = errOvh.QueryID
}
```

2024-10-15 15:09 UTC, mxpetit requested changes
agreed with @amstuta

2024-10-16 15:27 UTC, theredcat commented
@mxpetit @amstuta I've made some changes. I've preffered to split the error message in two cases to prevent an empty `Query ID :` when it's not available

2024-10-17 15:14 UTC, amstuta commented
Thanks for your contribution @theredcat :)

2024-10-17 15:15 UTC, amstuta approved these changes

2024-10-17 15:15 UTC, merged