Update dedicated server (and (me_)_installation_template )
ovh/terraform-provider-ovh pull request #639
Opened 2024-04-30 12:54 UTC by bigbigbang

# Description

Update of dedicated_me_installation_template
 - remove deprecated attributes
 - add attributes (end_of_install, subfamily, no_partitioning)

Update of type_installation_template

Add dedicated_installation_template data source

Remove resource me_ssh_key(s)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (improve existing resource(s) or datasource(s))
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

make testacc TESTARGS="-run TestAccInstallationTemplateDataSource_basic"
- [ ] Test A: `make testacc TESTARGS="-run TestAccMeInstallationTemplatesDataSource_basic"`
- [ ] Test B: `make testacc TESTARGS="-run TestAccInstallationTemplateDataSource_basic"`
- [ ] Test C: `make testacc TESTARGS="-run TestAccMeInstallationTemplateResource_basic"`

**Test Configuration**:
* Terraform version: `terraform version`: Terraform 1.6.6
* Existing HCL configuration you used: 
```hcl
data "ovh_dedicated_server" "server" {
  service_name = "nsxxxxx.ip-123-123-123.eu"
}

data "ovh_dedicated_installation_template" "ovhtemplate" {
  template_name = "win2019-dc_64"
}

output "template" {
  value = data.ovh_dedicated_installation_template.ovhtemplate
}
```

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings or issues
- [ ] I have added acceptance tests that prove my fix is effective or that my feature works
- [ ] New and existing acceptance tests pass locally with my changes
- [ ] I ran succesfully `go mod vendor` if I added or modify `go.mod` file

2024-05-02 08:22 UTC, amstuta requested changes

2024-05-02 08:32 UTC, bigbigbang commented on ovh/data_dedicated_installation_template.go
> +func dataSourceDedicatedInstallationTemplate() *schema.Resource {
no, it isn't the same API call ; one is me_installation_template -> return customer custom templates, and the other call dedicated_installation_template -> return OVH template

2024-05-02 14:21 UTC, amstuta commented on website/docs/d/dedicated_installation_template.html.markdown
> +* `bit_format`: Template bit format (32 or 64).
```suggestion
* `bit_format`: Template bit format (32 or 64)
```

(to remove or add on all fields to be consistent)

2024-05-02 14:22 UTC, amstuta commented on ovh/data_dedicated_installation_template_test.go
> +func TestAccInstallationTemplateDataSource_basic(t *testing.T) {
```suggestion
func TestAccDedicatedInstallationTemplateDataSource_basic(t *testing.T) {
```

2024-05-03 09:23 UTC, amstuta commented on .cds/terraform-provider-ovh.yml
> +      testargs: -run TestAccDedicatedInstallationTemplateDataSource_basic
```suggestion
      testargs: -run TestAccDedicatedInstallationTemplate
```

(we need to run `TestAccDedicatedInstallationTemplatesDataSource_basic` also)

2024-05-03 09:23 UTC, amstuta commented on ovh/data_dedicated_installation_template_test.go
> +				Config: config,
```suggestion
				Config: testAccInstallationTemplateDatasourceConfig_Basic,
```

and you can remove variable `config`

2024-05-03 13:21 UTC, amstuta approved these changes

2024-05-03 13:22 UTC, merged