Add loadbalancer log subscription
ovh/terraform-provider-ovh pull request #657
Opened 2024-05-24 12:46 UTC by Tiboau

# Manage log subscription for Loadbalancer

New Feature, add the possibility to the client to subscribe or get information about subscription

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvement (improve existing resource(s) or datasource(s))
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

# How Has This Been Tested?

export OVH_CLOUD_LOADBALANCER_ID_TEST=xxxxxx
export OVH_CLOUD_STREAM_ID_TEST=yyyyy

## DataSource
```
➜  make testacc TESTARGS="-run TestAccCloudProjectLoadBalancerGetLogSubscription_basic"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccCloudProjectLoadBalancerGetLogSubscription_basic -timeout 600m -p 10
?   	github.com/ovh/terraform-provider-ovh	[no test files]
?   	github.com/ovh/terraform-provider-ovh/ovh/helpers	[no test files]
?   	github.com/ovh/terraform-provider-ovh/ovh/types	[no test files]
=== RUN   TestAccCloudProjectLoadBalancerGetLogSubscription_basic
    provider_test.go:398: Read Cloud Project /cloud/project/bad3308a4b4d4dcba4d15d5b082d7225 -> status: 'ok', desc: 'Production'
--- PASS: TestAccCloudProjectLoadBalancerGetLogSubscription_basic (12.58s)
PASS
ok  	github.com/ovh/terraform-provider-ovh/ovh	12.595s
testing: warning: no tests to run
PASS
ok  	github.com/ovh/terraform-provider-ovh/ovh/helpers/hashcode	(cached) [no tests to run]
```

```
make testacc TESTARGS="-run TestAccCloudProjectLoadBalancerGetLogSubscriptions_basic"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccCloudProjectLoadBalancerGetLogSubscriptions_basic -timeout 600m -p 10
?   	github.com/ovh/terraform-provider-ovh	[no test files]
?   	github.com/ovh/terraform-provider-ovh/ovh/helpers	[no test files]
?   	github.com/ovh/terraform-provider-ovh/ovh/types	[no test files]
=== RUN   TestAccCloudProjectLoadBalancerGetLogSubscriptions_basic
    provider_test.go:398: Read Cloud Project /cloud/project/bad3308a4b4d4dcba4d15d5b082d7225 -> status: 'ok', desc: 'Production'
--- PASS: TestAccCloudProjectLoadBalancerGetLogSubscriptions_basic (12.71s)
PASS
ok  	github.com/ovh/terraform-provider-ovh/ovh	12.720s
testing: warning: no tests to run
PASS
ok  	github.com/ovh/terraform-provider-ovh/ovh/helpers/hashcode	(cached) [no tests to run]

```

Resource
```
make testacc TESTARGS="-run TestAccCloudProjectLoadBalancerLogSubscription_basic"      
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccCloudProjectLoadBalancerLogSubscription_basic -timeout 600m -p 10
?   	github.com/ovh/terraform-provider-ovh	[no test files]
?   	github.com/ovh/terraform-provider-ovh/ovh/helpers	[no test files]
?   	github.com/ovh/terraform-provider-ovh/ovh/types	[no test files]
=== RUN   TestAccCloudProjectLoadBalancerLogSubscription_basic
    provider_test.go:398: Read Cloud Project /cloud/project/bad3308a4b4d4dcba4d15d5b082d7225 -> status: 'ok', desc: 'Production'
--- PASS: TestAccCloudProjectLoadBalancerLogSubscription_basic (12.22s)
PASS
ok  	github.com/ovh/terraform-provider-ovh/ovh	12.233s
testing: warning: no tests to run
PASS
ok  	github.com/ovh/terraform-provider-ovh/ovh/helpers/hashcode	0.002s [no tests to run]
➜  terraform-provider-ovh git:(add-loadbalancer-log-subscription) ✗ 

```

**Test Configuration**:
* Terraform version: `terraform version`: Terraform vx.y.z
* Existing HCL configuration you used: 
```hcl

resource "ovh_cloud_project_region_loadbalancer_log_subscription" "CreateLogSubscription" {
  service_name = "xxxx"
  region_name = "yyyy"
  loadbalancer_id = "aaa"
  kind = "haproxy"
  stream_id = "ssss"
}

data "ovh_cloud_project_region_loadbalancer_log_subscription" "sub" {
   service_name = "xxxx"
   region_name = "yyyy"
   loadbalancer_id = "aaa"
   subscription_id = ovh_cloud_project_region_loadbalancer_log_subscription.CreateLogSubscription.id
}

data "ovh_cloud_project_region_loadbalancer_log_subscriptions" "titi" {
   service_name = "xxxx"
   region_name = "yyyy"
   loadbalancer_id = "aaa"
}
```

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] I have added acceptance tests that prove my fix is effective or that my feature works

2024-05-27 10:23 UTC, amstuta requested changes

2024-05-27 10:23 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscription.markdown
> +* `service_name` - The id of the public cloud project. If omitted, the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used. **Changing this value recreates the resource.**
```suggestion
* `service_name` - The id of the public cloud project. If omitted, the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
```

2024-05-27 10:23 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscription.markdown
> +* `region_name` - A valid OVHcloud public cloud region name in which the loadbalancer will be available. Ex.: "GRA11". **Changing this value recreates the resource.**
```suggestion
* `region_name` - A valid OVHcloud public cloud region name in which the loadbalancer is available. Ex.: "GRA11".
```

2024-05-27 10:23 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscription.markdown
> +* `region_name` - A valid OVHcloud public cloud region name in which the loadbalancer will be available. Ex.: "GRA11".
```suggestion
* `region_name` - A valid OVHcloud public cloud region name in which the loadbalancer is available. Ex.: "GRA11". 
```

2024-05-27 10:23 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscriptions.markdown
> +data "ovh_cloud_project_region_loadbalancer_log_subscription" "sub" {
```suggestion
data "ovh_cloud_project_region_loadbalancer_log_subscriptions" "subs" {
```

2024-05-27 10:23 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscriptions.markdown
> +  subscription_id = "zzzzzzzz-yyyy-xxxx-wwww-vvvvvvvvvvvv"
```suggestion
```

2024-05-27 10:23 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscriptions.markdown
> +* `subscription` - Subscription id
```suggestion
```

2024-05-27 10:23 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscriptions.markdown
> +* `region_name` - A valid OVHcloud public cloud region name in which the loadbalancer will be available. Ex.: "GRA11".
```suggestion
* `region_name` - A valid OVHcloud public cloud region name in which the loadbalancer is available. Ex.: "GRA11".
```

2024-05-27 10:23 UTC, amstuta commented on website/docs/r/cloud_project_region_loadbalancer_log_subscription.markdown
> +Create a simple Kubernetes cluster in `GRA7` region:
to update

2024-05-27 10:23 UTC, amstuta commented on website/docs/r/cloud_project_region_loadbalancer_log_subscription.markdown
> +* `kind` - haproxy
desc to update

2024-05-27 10:23 UTC, amstuta commented on website/docs/r/cloud_project_region_loadbalancer_log_subscription.markdown
> +* `loadbalancer_id` - Loadbalancer id to get the logs
```suggestion
* `loadbalancer_id` - Loadbalancer id to get the logs. **Changing this value recreates the resource.**
```

2024-05-27 10:23 UTC, amstuta commented on website/docs/r/cloud_project_region_loadbalancer_log_subscription.markdown
> +* `stream_id` - Data stream id to use for the subscription
```suggestion
* `stream_id` - Data stream id to use for the subscription. **Changing this value recreates the resource.**
```

2024-05-27 10:23 UTC, amstuta commented on website/docs/r/cloud_project_region_loadbalancer_log_subscription.markdown
> +* `kind` - haproxy
will also need `**Changing this value recreates the resource.**`

2024-05-27 13:30 UTC, Tiboau commented on ovh/data_cloud_project_region_loadbalancer_log_subscription.go
> +	d.SetId(response.StreamID)
Currently, you can't. You can have only one subscription for one stream Client::Conflict::SubscriptionAlreadyExists

2024-05-30 14:04 UTC, amstuta commented on ovh/data_cloud_project_region_loadbalancer_log_subscription.go
> +	d.SetId(response.StreamID)
OK, but even if you can't do this, it would be logical that the ID is the subscription id since the datasource is the subscription

2024-05-30 14:09 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscriptions.markdown
> +Get information about a subscription to a Managed Loadbalance Logs Service in a public cloud project.
```suggestion
Get information about subscriptions to a Managed Loadbalancer Logs Service in a public cloud project.
```

2024-05-30 14:09 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscription.markdown
> +Get information about a subscription to a Managed Loadbalance Logs Service in a public cloud project.
```suggestion
Get information about a subscription to a Managed Loadbalancer Logs Service in a public cloud project.
```

2024-06-04 14:33 UTC, amstuta commented on ovh/data_cloud_project_region_loadbalancer_log_subscription.go
> +	d.SetId(response.StreamID)
🆙

2024-06-04 14:34 UTC, amstuta commented on ovh/data_cloud_project_region_loadbalancer_log_subscriptions.go
> +		"/cloud/project/%s/region/%s/loadbalancing/loadbalancer/%s/log/subscription",
🆙

2024-06-04 14:34 UTC, amstuta commented on ovh/data_cloud_project_region_loadbalancer_log_subscriptions_test.go
> +
🆙

2024-06-04 14:34 UTC, amstuta commented on ovh/data_cloud_project_region_loadbalancer_log_subscriptions_test.go
> +func testAccCheckGetSubscriptions(t *testing.T) {
🆙

2024-06-04 14:35 UTC, amstuta commented on ovh/resource_cloud_project_region_loadbalancer_log_subscription.go
> +				Description: "Service name of the resource representing the id of the cloud project.",
🆙

2024-07-05 12:42 UTC, amstuta requested changes

2024-07-05 12:42 UTC, amstuta commented on ovh/data_cloud_project_region_loadbalancer_log_subscription_test.go
> +					resource.TestCheckResourceAttrSet("data.ovh_cloud_project_region_loadbalancer_log_subscription.test", "created_at"),
you should check more fields, for example the `kind` that you set explicitly to `haproxy`

2024-07-05 12:42 UTC, amstuta commented on ovh/data_cloud_project_region_loadbalancer_log_subscriptions.go
> +		"/cloud/project/%s/region/%s/loadbalancing/loadbalancer/%s/log/subscription",
still to fix

2024-07-05 12:42 UTC, amstuta commented on ovh/data_cloud_project_region_loadbalancer_log_subscriptions_test.go
> +
🆙

2024-07-05 12:42 UTC, amstuta commented on ovh/resource_cloud_project_kube.go
> +		endpoint := fmt.Sprintf("/cloud/project/%s/kube/%s/updateLoadBalancersSubnetId", serviceName, d.Id())
all parameters must be pathEscaped

2024-07-05 12:42 UTC, amstuta commented on ovh/resource_cloud_project_network_private_subnet.go
> +	endpoint := fmt.Sprintf("/cloud/project/%s/network/private/%s/subnet/%s", serviceName, networkId, id)
please PathEscape all params

2024-07-05 12:42 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscription.markdown
> +
```suggestion
```

2024-07-05 12:42 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscription.markdown
> +* `subscription` - Subscription id
```suggestion
* `subscription_id` - Subscription id
```

2024-07-05 12:42 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscription.markdown
> +* `kind` - haproxy
Please put a real description

2024-07-05 12:42 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscriptions.markdown
> +data "ovh_cloud_project_region_loadbalancer_log_subscription" "sub" {
🆙

2024-07-05 12:42 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscriptions.markdown
> +  subscription_id = "zzzzzzzz-yyyy-xxxx-wwww-vvvvvvvvvvvv"
🆙

2024-07-05 12:42 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscriptions.markdown
> +* `subscription` - Subscription id
🆙

2024-07-05 12:42 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscriptions.markdown
> +* `kind` - (Optional) haproxy
Add a real description

2024-07-19 14:03 UTC, amstuta commented on ovh/data_cloud_project_region_loadbalancer_log_subscriptions.go
> +		query = fmt.Sprintf("?kind=%s", url.PathEscape(kind))
```suggestion
		query = fmt.Sprintf("?kind=%s", url.QueryEscape(kind))
```

2024-07-19 14:27 UTC, amstuta commented on ovh/data_cloud_project_region_loadbalancer_log_subscriptions_test.go
> +	service_name = ovh_cloud_project_region_loadbalancer_log_subscription.subscription.service_name
still true

2024-07-19 14:27 UTC, amstuta commented on ovh/data_cloud_project_region_loadbalancer_log_subscriptions_test.go
> +func testAccCheckGetSubscriptions(t *testing.T) {
still true

2024-07-19 14:27 UTC, amstuta commented on ovh/resource_cloud_project_region_loadbalancer_log_subscription.go
> +		if k != "id" {
🆙

2024-07-19 14:27 UTC, amstuta commented on ovh/resource_cloud_project_region_loadbalancer_log_subscription.go
> +	err := config.OVHClient.DeleteWithContext(ctx, endpoint, res)
🆙

2024-07-19 14:27 UTC, amstuta commented on ovh/resource_cloud_project_region_loadbalancer_log_subscription_test.go
> +				Check: resource.ComposeTestCheckFunc(
🆙

2024-07-19 14:27 UTC, amstuta commented on ovh/resource_cloud_project_region_loadbalancer_log_subscription_test.go
> +	testAccPreCheckCloud(t)
🆙

2024-07-19 14:27 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscription.markdown
> +* `subscription` - Subscription id
🆙

2024-07-29 14:22 UTC, amstuta commented on website/docs/d/cloud_project_region_loadbalancer_log_subscriptions.markdown
> +data "ovh_cloud_project_region_loadbalancer_log_subscription" "subs" {
```suggestion
data "ovh_cloud_project_region_loadbalancer_log_subscriptions" "subs" {
```

2024-07-29 14:25 UTC, merged