Clean test and example on cloud_project_kube resource with private network
ovh/terraform-provider-ovh pull request #775
Opened 2024-11-19 10:55 UTC by yomovh

# Description

* remove `ovh_vrack_cloudproject` resource  since from Q2 2024 all public cloud projects (existing or new) have a vrach attached to them.
* remove unnecessary `depends_on` that terraform / opentofu engine can manage.
* add `node_subnet_id` to avoid race condition in terraform execution plan if the subnet & the kube cluster are created in // resulting in error like `Private network xxx does not have any subnet`
* add a managed gateway
* in the test, add a random vlanId for a smoother run.

## Type of change

Please delete options that are not relevant.

- [ X] Documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ X] Test A: `make testacc TESTARGS="-run TestAccCloudProjectKubeVRack"`

**Test Configuration**:
```bash
 >tofu -version
OpenTofu v1.8.4
on darwin_arm64
```

2024-11-21 09:28 UTC, nicolaslacroux approved these changes

2024-11-21 10:33 UTC, Lucasgranet requested changes

2024-11-21 10:33 UTC, Lucasgranet commented on ovh/resource_cloud_project_kube_test.go
>  		DefaultVrackGateway:            "10.4.0.1",
```suggestion
		DefaultVrackGateway:            "",
```
Let's the DHCP server gives the GatewayIP.
(ATM, the KubeVRack with a gateway is not working, the provided DefaultVrackGateway is not matching the deployed one)

2024-11-27 16:51 UTC, Lucasgranet approved these changes
LGTM

2024-11-28 08:39 UTC, amstuta approved these changes

2024-11-28 08:39 UTC, merged